var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
var isFirefox="undefined"!==typeof InstallTrigger,isSafari=/^((?!chrome|android).)*safari/i.test(navigator.userAgent),inputText="",recorderActive=!1,attrArr=",withid,withclass,withname,withplaceholder,withtext",_document="",frameOriframe="";
function getDocument(){_document="";if(document.querySelector("*[xpathtest='1']"))_document=document;else try{getAlliframe(document);for(var a=Object.keys(allIframes).length,b=0;b<a;b++)for(var c=allIframes["iframe"+b],d=0;d<c.length;d++)try{if(c[d].contentWindow.document.querySelector("*[xpathtest='1']")){_document=c[d].contentWindow.document;frameOriframe="iframe";return}}catch(e){}}catch(e){}}
function iframeOfFrame(a){for(var b=document.querySelectorAll("iframe"),c=0;c<b.length;c++)try{if(b[c].contentWindow.document=a.ownerDocument){frameOriframe="iframe";return}}catch(e){}var d=document.querySelectorAll("frame");for(c=0;c<d.length;c++)try{if(b[c].contentWindow.document=a.ownerDocument){frameOriframe="frame";break}}catch(e){}}function isEven(a){return 0==a%2}function isOdd(a){return 1==Math.abs(a%2)}
function isSpecialCharValidForSelector(a){return!/[~`!#$%\^&*+=\-\(\)\\';,{}|\\":<>\?]/g.test(a)}function validAfterClosedSquare(a){a=a.split("]");for(var b=1;b<=a.length-1;b++)if(a[b].charAt(0)&&"/"!=a[b].charAt(0)&&"["!=a[b].charAt(0))return!1;return!0}
function errorInSelector(a,b){var c=/^[A-Za-z]+$/;if(b.includes("///")||b.includes("////")||b.includes("/////")||b.includes("//////"))return"more than 2 / together not allowed";if("//"==b)return a.includes("css")?"// not allowed.":"add tagName after //";if("/"==b.charAt(b.length-1))return a.includes("css")?"forward slash / not allowed.":"add tagName after forward slash /";var d=b.match(/'/g)?b.match(/'/g).length:0;if(isOdd(d))return"single quote ' missing";d=b.match(/"/g)?b.match(/"/g).length:0;if(isOdd(d))return'double quote " missing';
d=b.match(/\(/g)?b.match(/\(/g).length:0;var e=b.match(/\)/g)?b.match(/\)/g).length:0;if(d!=e)return d>e?"close parenthesis ) missing":"open parenthesis ( missing";d=b.match(/\[/g)?b.match(/\[/g).length:0;e=b.match(/\]/g)?b.match(/\]/g).length:0;if(d!=e)return d>e?"close square bracket ] missing":"open square bracket [ missing";d=b.match(/:/g)?b.match(/:/g).length:0;if(isOdd(d))return a.includes("css")?"colon : not allowed.":"colon : missing";d=/[^[\]]+(?=])/g;if(b.includes("[")&&b.includes("]")&&
!d.exec(b))return"Value inside square brackets [] missing";if((2<b.split("]").length||2==b.split("]").length&&b.split("]")[1])&&!validAfterClosedSquare(b))return a.includes("css")?"after ] only [ allowed":"after ] only / and [ allowed";if(b.includes("::")&&!b.split("::")[1])return"tagName missing after ::";if(b.split("::")[1]&&!c.test(b.split("::")[1]))return"only tagName allowed after ::";if(b.includes("/"))for(b=b.replaceAll("//","/"),d=b.split("/"),e=0;e<d.length-1;e++)if((!d[e]||!c.text(d[e].charAt(0))&&
"."!=d[e].charAt(0)&&"*"!=d[e].charAt(0))&&d[e])return"after / only . * and tagname allowed";if(/[^[\]]+(?=])/g.exec(b)&&(c=replaceAll(b,"["+/[^[\]]+(?=])/g.exec(b)[0]+"]",""),!isSpecialCharValidForSelector(c)))return"special char not allowed outside []";/\(([^)]+)\)/.exec(b)&&replaceAll(b,"("+/\(([^)]+)\)/.exec(b)[0]+")","");return b.includes(";")?"semicolon ; not allowed":b.includes("{")||b.includes("}")?"curly brackets { } not allowed":b.includes("normalise-space")?"wrong spelling, use 'normalize' in place of 'normalise'":
"Check the syntax & spelling."}function replaceAll(a,b,c){return a.split(b).join(c)}var oldNodes=[],oldAttribute="",allNodes=[],idChecked="";_document="";
var pageUrl="websiteUrl-"+document.URL,inspectedElement="",elementInShadowDom="",element="",suggestedFlag=!1,passResultsToDevtoolsScript=function(a,b,c,d){try{element.nodeName.toLowerCase()}catch(k){}b.includes("//text()")&&(b=b.replace("//text()","//*[text()")+"]");_document=_document?_document:document;a="."===b?"xpath":a;var e="";try{if(!a.includes("xpath")&&"."!==b||elementInShadowDom)var f=elementInShadowDom?inspectedElement.getRootNode().host.shadowRoot.querySelectorAll(b):_document.querySelectorAll(b);
else{if(absXpathForInspected&&(e=_document.evaluate(absXpathForInspected,_document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0),(isSVGChild(e)||"svg"==e.nodeName.toLowerCase())&&b.includes("/svg"))){chrome.runtime.sendMessage({count:"wrong"+a+"errorInfoInvalid svg xpath format."});for(var h=0;h<oldNodes.length;h++)deleteAttribute(oldNodes[h],a,c);oldNodes=[];allNodes=[];return}f=_document.evaluate(b,_document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null)}}catch(k){b?(d=errorInSelector(a,
b),a="css"==a?"cssSelector":a,elementInShadowDom&&(a.includes("xpath")||"."===b)&&(a="cssSelector",d="xpath doesn't support ShadowDOM."),chrome.runtime.sendMessage({count:"wrong"+a+"errorInfo"+d})):chrome.runtime.sendMessage({count:"blank"});for(h=0;h<oldNodes.length;h++)deleteAttribute(oldNodes[h],a,c);oldNodes=[];allNodes=[];return}e=a.includes("xpath")?f.snapshotLength:f.length;for(h=0;h<oldNodes.length;h++)deleteAttribute(oldNodes[h],a,c);oldNodes=[];allNodes=[];for(h=0;h<e;h++){var g=a.includes("xpath")?
f.snapshotItem(h):f[h];0===h&&"/"!==b&&"."!==b&&"/."!==b&&"//."!==b&&"//.."!==b&&1==g.nodeType&&(isFirefox?g.scrollIntoView({behavior:"smooth",block:"center",inline:"nearest"}):g.scrollIntoViewIfNeeded());oldNodes.push(g);oldAttribute=a;1==g.nodeType?(appendAttribute(g,a,h+1),allNodes.push(g.outerHTML)):(2==g.nodeType||3==g.nodeType)&&0<g.textContent.trim().length?allNodes.push(g.textContent.trim()):void 0==g.value?allNodes.push(" "):allNodes.push(g.name+'="'+g.value+'"')}chrome.runtime.sendMessage({count:allNodes});
a.includes("xpath")&&1<e&&(e=_document.evaluate(absXpathForInspected,_document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0),(f=e.getAttribute("xpath"))&&chrome.runtime.sendMessage({count:"1-sanjayMatchingNode--sanjayXpathIndex-("+b+")["+f+"]"}));if(_document!==document){"onlyEditor"!==hubMode&&(b=_document,f=["frame",getIframeXpath(_document),parentiframeXpath],parentiframeXpath=[],chrome.runtime.sendMessage({count:f}),_document=b);try{var l=_document.querySelectorAll("style[selectorshub]");
for(h=0;h<l.length;h++)l[h].remove()}catch(k){}h="[xpath], [css]{outline: 2px dashed #00bcd4 !important}";l=_document.createElement("style");l.setAttribute("SelectorsHub","sh");l.textContent=h;_document.documentElement.appendChild(l);h='[xpath="1"], [css="1"]{outline:2px dashed #f29a00 !important}';l=_document.createElement("style");l.setAttribute("SelectorsHub","sh");l.textContent=h;_document.documentElement.appendChild(l)}else if(elementInShadowDom){try{for(l=inspectedElement.getRootNode().host.shadowRoot.querySelectorAll("style[selectorshub]"),
h=0;h<l.length;h++)l[h].remove()}catch(k){}h="[xpath], [css]{outline: 2px dashed #0715f7f7 !important}";l=_document.createElement("style");l.setAttribute("SelectorsHub","sh");l.textContent=h;inspectedElement.getRootNode().host.shadowRoot.appendChild(l);h='[xpath="1"], [css="1"]{outline:2px dashed #ffa500 !important}';l=_document.createElement("style");l.setAttribute("SelectorsHub","sh");l.textContent=h;inspectedElement.getRootNode().host.shadowRoot.appendChild(l)}pageUrl="websiteUrl-"+document.URL;
if(c&&!elementInShadowDom){c=_document.querySelector("["+a+'="1"]');a=["",0];try{suggestedFlag=!0,createAbsXpath(c),a=createCssSelector(c,d)}catch(k){}suggestedFlag=!1;1!==a[1]&&(a=createRelXpath(c,d));d=["suggestedSelector",a];0!=a[1]&&chrome.runtime.sendMessage({count:d})}},appendAttribute=function(a,b,c){b.includes("xpath")&&(b="xpath");try{a.setAttribute(b,c)}catch(d){}},deleteAttribute=function(a,b,c){try{b=oldAttribute,a.removeAttribute(b),a.nodeName.toLowerCase().includes("svg")?a.style.border=
"":a.style.outline=""}catch(d){}};function getElementsByXPath(a){try{var b=[],c=document.evaluate(a,document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null);a=0;for(var d=c.snapshotLength;a<d;++a)b.push(c.snapshotItem(a));return b.length}catch(e){console.warn(e,"NOT VALID")}}function calculateElements(a){if(!a.xpath)return!1;var b=getElementsByXPath(a.xpath);b&&chrome.runtime.sendMessage({type:"elementsCount",id:a.id,elementCount:b});return!1}var allDocuments=[];
function getAllDocument(){allDocuments.push(document);for(var a=document.querySelectorAll("iframe"),b=0;b<a.length;b++)try{allDocuments.push(a[b].contentWindow.document),frameOriframe="iframe"}catch(c){}a=document.querySelectorAll("frame");for(b=0;b<a.length;b++)try{allDocuments.push(a[b].contentWindow.document),frameOriframe="frame"}catch(c){}}var contextElement=null,contextSelectors=[];
setTimeout(function(){function a(b){contextSelectors=[];b=isFirefox?b.composedPath()[0]:isSafari?b.composedPath()[0]:b.path[0];createSelectorsForContextMenu(b);chrome.runtime.sendMessage({contextSelectors:contextSelectors})}pageUrl.includes("https://docs.google.com/")||pageUrl.includes("https://drive.google.com/")||chrome.storage.local.get("contextMenu",function(b){if((contextMenu=b.contextMenu?b.contextMenu:"active")&&!contextMenu.includes("inactive"))for(b=0;b<allDocuments.length;b++)allDocuments[b].addEventListener("contextmenu",
a,!0)});chrome.storage.local.get("relXpathChecked",function(b){relXpathChecked=b.relXpathChecked?b.relXpathChecked:"relXpathOn"});chrome.storage.local.get("cssSelectorChecked",function(b){cssSelectorChecked=b.cssSelectorChecked?b.cssSelectorChecked:"cssSelectorOff"});getAllDocument();isSafari&&document.addEventListener("contextmenu",a,!0)},3E3);var generateContextMenu=!1;
function createSelectorsForContextMenu(a){_document=a.ownerDocument;generateContextMenu=!0;var b="";elementInShadowDom=isInShadow(a);chooseAttrsForXpath=["withid","withclass","withname","withplaceholder","withtext"];var c=a.nodeName.toLowerCase();c.includes("style")||c.includes("script")?(contextSelectors[0]="This is a "+c+" tag. For "+c+" tag, no need to write Selectors. :P",contextSelectors[1]="This is a "+c+" tag. For "+c+" tag, no need to write Selectors. :P",contextSelectors[2]="This is a "+
c+" tag. For "+c+" tag, no need to write Selectors. :P",contextSelectors[3]="This is a "+c+" tag. For "+c+" tag, no need to write Selectors. :P"):(absXpath=createAbsXpath(a)[0],"relXpathOn"==relXpathChecked&&(contextSelectors[0]=b+createRelXpath(a,chooseAttrsForXpath)[0],globalRelXpath=contextSelectors[0]),"cssSelectorOn"==cssSelectorChecked&&(contextSelectors[1]=createCssSelector(a,chooseAttrsForXpath)[0].trim(),contextSelectors[2]='document.querySelector("'+contextSelectors[1].trim()+'")'),contextSelectors[3]=
b+absXpath,a.ownerDocument!==document?(b="This element is in iframe - ",contextSelectors[0]=b+contextSelectors[0],contextSelectors[1]=b+contextSelectors[1],contextSelectors[2]=b+contextSelectors[2],contextSelectors[3]=b+contextSelectors[3]):elementInShadowDom&&(b="This element is in shadowDOM - ",contextSelectors[1]=b+contextSelectors[1],contextSelectors[2]=b+contextSelectors[2],elementInShadowDom=!1));generateContextMenu=!1}
var contextMenu="active",relXpathChecked="relXpathOn",cssSelectorChecked="cssSelectorOff";
chrome.runtime.onMessage.addListener(function(a,b,c){a&&"debuggerOn"===a.name&&setTimeout(function(){debugger},5E3);a&&"toggle-btn inactive"===a.name?(document.removeEventListener("contextmenu",rightClick,!0),contextMenu="inactive",chrome.storage.local.set({contextMenu:contextMenu},function(){})):a&&"toggle-btn active"===a.name&&(contextMenu="active",buildContextMenuResult(),chrome.storage.local.set({contextMenu:contextMenu},function(){}));a&&"relXpathOn"===a.name?(relXpathChecked="relXpathOn",chrome.storage.local.set({relXpathChecked:relXpathChecked},
function(){})):a&&"relXpathOff"===a.name&&(relXpathChecked="relXpathOff",chrome.storage.local.set({relXpathChecked:relXpathChecked},function(){}));a&&"cssSelectorOn"===a.name?(cssSelectorChecked="cssSelectorOn",chrome.storage.local.set({cssSelectorChecked:cssSelectorChecked},function(){})):a&&"cssSelectorOff"===a.name&&(cssSelectorChecked="cssSelectorOff",chrome.storage.local.set({cssSelectorChecked:cssSelectorChecked},function(){}));a&&"calcElements"===a.name&&calculateElements(a.data);a&&a.attrArray&&
(attrArr=a.attrArray);a&&a.openStudio&&(recorderActive=!0,attachEvents());a&&a.stopRecording&&(recorderActive=!1,deattachEvents(),browser.runtime.sendMessage(chrome.runtime.id,{message:"StopRecording"}));a&&a.closed&&(recorderActive=!1,deattachEvents(),browser.runtime.sendMessage(chrome.runtime.id,{message:"DeattachStudio"}));"recorderAttr"===a.name&&browser.runtime.sendMessage(chrome.runtime.id,{type:"recorderAttr",data:a.data});"updateCPAttr"===a.name&&browser.runtime.sendMessage(chrome.runtime.id,
{type:"updateCPAttr",data:a.data});if(a&&"downloadReport"===a.type&&a.data){var d="",e=window.navigator.userAgent.includes("Windows");a.data.forEach(function(h){d+=e?h.join(","):h.join("\t");d+="\n"});b=window.document.createElement("a");b.href=window.URL.createObjectURL(new Blob([d],{type:"data:application/vnd.ms-excel;base64,"}));b.download=e?a.fileName+".csv":a.fileName+".xls";document.body.appendChild(b);b.click();document.body.removeChild(b)}tempXpath="";this.indexes=[];this.matchIndex=[];var f=
a.chooseAttrs;if(!a.openStudio&&a.name.includes("Editor"))setTimeout(function(){try{hubMode=a.name;getDocument();element="";try{element=getInspectedElement(),elementInShadowDom=!1}catch(h){}element||(elementInShadowDom=(element=replaceShadowDomsWithHtml(document.body))?!0:!1,inspectedElement=element,_document=document);prepareListOfAttrText(element)}catch(h){}},50),a.name.includes("generatorAndEditor")&&(hubMode=a.name,setTimeout(function(){onInspectElementClick(element,f,hubMode)},50));else if(_document){(a.xpath||
""===a.xpath)&&a.name.includes("highlight-element")&&(a.xpath[1]?a.xpath[1].charAt(0).includes("/")||a.xpath[1].charAt(0).includes("(")||a.xpath[1].substr(0,2).includes("./")?a.name="xpath":a.name="css":a.name="xpath",a.xpath[1]&&passResultsToDevtoolsScript(a.name,a.xpath[1],a.xpath[2],a.xpath[3]));"xpath"===a.name&&(b=_document.querySelector('[xpath="'+a.index+'"]'))&&(c=b.nodeName.toLowerCase().includes("svg")?"border":"outline",b.style.cssText=c+":2px solid orangered !important",isFirefox?b.scrollIntoView({behavior:"smooth",
block:"end",inline:"nearest"}):b.scrollIntoViewIfNeeded());"xpath-remove"===a.name&&(b=_document.querySelector('[xpath="'+a.index+'"]'))&&(b.nodeName.toLowerCase().includes("svg")?b.style.border="":b.style.outline="");if("css"===a.name){b="";if(elementInShadowDom)try{b=inspectedElement.getRootNode().host.shadowRoot.querySelector('[css="'+a.index+'"]')}catch(h){}else b=_document.querySelector('[css="'+a.index+'"]');b&&(c=b.nodeName.toLowerCase().includes("svg")?"border":"outline",b.style.cssText=c+
":2px solid orangered !important",isFirefox?b.scrollIntoView({behavior:"smooth",block:"end",inline:"nearest"}):b.scrollIntoViewIfNeeded())}"css-remove"===a.name&&(b="",b=elementInShadowDom?inspectedElement.getRootNode().host.shadowRoot.querySelector('[css="'+a.index+'"]'):_document.querySelector('[css="'+a.index+'"]'))&&(b.nodeName.toLowerCase().includes("svg")?b.style.border="":b.style.outline="");a.xpath=""}});
function createIdSelector(a){_document=a.ownerDocument;if(a.id&&!elementInShadowDom){var b=a.id;b=deleteLineGap(b);var c="//*[@id='"+b+"']";a=elementInShadowDom?cssSelectorMatchingNode(a,"#"+b):_document.evaluate(c,_document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength;c=[];c.push(b);c.push(a);return c}}
function createClassNameSelector(a){_document=a.ownerDocument;if(a.attributes["class"]){var b=a.attributes["class"].value;b=deleteLineGap(b);var c="."+b.replace(/ /g,".");a=cssSelectorMatchingNode(a,c);c=[];c.push(b);c.push(a);return c}}function createNameSelector(a){_document=a.ownerDocument;if(a.name){var b=a.name;b=deleteLineGap(b);var c=a.nodeName.toLowerCase()+"[name='"+b+"']";a=cssSelectorMatchingNode(a,c);c=[];c.push(b);c.push(a);return c}}
function createTagNameSelector(a){_document=a.ownerDocument;var b=a.nodeName.toLowerCase(),c=a.nodeName.toLowerCase();a=cssSelectorMatchingNode(a,c);c=[];c.push(b);c.push(a);return c}
function createLinkTextSelector(a){_document=a.ownerDocument;if("a"===a.nodeName.toLowerCase()&&!elementInShadowDom&&(a=[].reduce.call(a.childNodes,function(d,e){return d+(3===e.nodeType?e.textContent:"")},"").trim(),0!==a.length)){var b="//a[text()='"+a+"']";a.includes("'")&&(b='//a[text()="'+a+'"]');b=_document.evaluate(b,_document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength;var c=[];c.push(a);c.push(b);return c}}
function createPartialLinkTextSelector(a){_document=a.ownerDocument;if("a"===a.nodeName.toLowerCase()&&!elementInShadowDom&&(a=[].reduce.call(a.childNodes,function(d,e){return d+(3===e.nodeType?e.textContent:"")},"").trim(),0!==a.length)){5<a.length&&(a=a.slice(0,a.length-2).slice(0,20));var b="//a[contains(text(),'"+a+"')]";a.includes("'")&&(b='//a[contains(text(),"'+a+'")]');b=_document.evaluate(b,_document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength;var c=[];c.push(a);c.push(b);
return c}}function buildAbsXpath(a){if("html"===a.nodeName.toLowerCase())return"/html[1]";if("body"===a.nodeName.toLowerCase())return"/html[1]/body[1]";for(var b=0,c=a.parentNode.childNodes,d=0;d<c.length;d++){var e=c[d];if(e===a){var f=buildAbsXpath(a.parentNode)+"/"+a.nodeName.toLowerCase()+"["+(b+1)+"]";break}1===e.nodeType&&e.nodeName.toLowerCase()===a.nodeName.toLowerCase()&&b++}return f}var absXpath="";
function createAbsXpath(a){var b=a.nodeName.toLowerCase();b.includes("#comment")?absXpath="This is a comment and selectors can't be generated for comment.":b.includes("<pseudo:")?absXpath="This is a pseudo element and selectors can't be generated for pseudo element.":b.includes("style")||b.includes("script")?absXpath="This is a "+b+" tag. For "+b+" tag, no need to write xpath. :P":b.includes("#document-fragment")?absXpath="This is a shadow-root and xpath can't be written for it. Please inspect an element.":
elementInShadowDom?(absXpath="This element is inside Shadow DOM & for such elements XPath won't support.",absXpath=shadowDOMOpenOrClosed.includes("closed")?"This element is inside closed Shadow DOM which is inaccessible so for such elements we can't verify/write selectors.":absXpath):absXpath=buildAbsXpath(a);a=0;if(absXpath.includes("svg")){b=absXpath.split("svg")[0];for(var c=absXpath.split("svg")[1].split("/"),d="",e=0;e<c.length;e++)d=0===e?"*[local-name()='svg']"+c[e]:d+"/*[name()='"+c[e].split("[")[0]+
"']["+c[e].split("[")[1];absXpath=b+d}try{a=_document.evaluate(absXpath,_document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength}catch(f){a=0}b=[];b.push(absXpath);b.push(a);return b}var tempXpath="",indexes=[],matchIndex=[],containsFlag=!1;function deleteLineGap(a){a&&(a=0<a.split("\n")[0].length?a.split("\n")[0]:a.split("\n")[1]);return a}var containsText="",equalsText="";
function deleteGarbageFromInnerText(a){a=deleteLineGap(a);a=a.split(/[^\u0000-\u00ff]/).reduce(function(b,c){return b.length>c.length?b:c},"").trim();return a=a.split("/")[0].trim()}function isSVGChild(a){for(var b=0;4>b;b++)if(a.parentNode){if("svg"===a.parentNode.nodeName.toLowerCase())return!0;a=a.parentNode}}function getPrecedingSiblings(a){for(var b=[];a=a.previousSibling;)3!==a.nodeType&&8!==a.nodeType&&b.push(a.nodeName.toLowerCase());return b}
function getFollowingSiblings(a){for(var b=[];a=a.nextSibling;)3!==a.nodeType&&8!==a.nodeType&&b.push(a.nodeName.toLowerCase());return b}function getAllSiblings(a){var b=[];a=a.parentNode.firstChild;do 3!==a.nodeType&&8!==a.nodeType&&b.push(a.nodeName.toLowerCase());while(a=a.nextSibling);return b}
function getAllAncestors(a){for(var b=[];a.parentNode&&"#document"!=a.parentNode.nodeName.toLowerCase()&&"html"!=a.parentNode.nodeName.toLowerCase();)3!==a.parentNode&&8!==a.parentNode&&(a=a.parentNode,b.push(a.nodeName.toLowerCase()));return b}function getAllDescendants(a){a=a.getElementsByTagName("*");for(var b=[],c=0;c<a.length;c++)3!=a[c].nodeType&&8!=a[c].nodeType&&b.push(a[c].nodeName.toLowerCase());return b}
function getAllChildren(a){a=a.children;for(var b=[],c=0;c<a.length;c++)3!=a[c].nodeType&&8!=a[c].nodeType&&b.push(a[c].nodeName.toLowerCase());return b}function containsNewLineBlankSpaceStartEnd(a){return/\r|\n/.exec(a)||" "==a.charAt(0)||" "==a.charAt(a.length-1)?!0:!1}function placeZerosAtEnd(a){return a.filter(isntZero).concat(a.filter(isZero))}function isntZero(a){return 0<a.charAt(0)}function isZero(a){return 0==a.charAt(0)}
var listOfTextAndAttr=[],xpathListOfTextAndAttr=[],cssListOfTextAndAttr=[],hubMode="",absXpathForInspected="";
function prepareListOfAttrText(a){isFirefox||(_document=a.ownerDocument,inspectedElement=a,elementInShadowDom=isInShadow(a),iframeOfFrame(a));listOfTextAndAttr=[];xpathListOfTextAndAttr=[];cssListOfTextAndAttr=[];listOfTextAndAttr.push("z$*[shub]");var b="",c="",d="",e=b="",f="",h=a.nodeName.toLowerCase();try{d=[].reduce.call(a.childNodes,function(l,k){return l+(3===k.nodeType?k.textContent:"")},"").trim(),b=[].reduce.call(a.childNodes,function(l,k){return l+(3===k.nodeType?k.textContent:"")},""),
e=a.innerText.trim(),e=deleteLineGap(e),e=d!=e?e:""}catch(l){}elementInShadowDom||(h.includes("svg")||isSVGChild(a)?(f="//*[local-name()='"+h+"']",xpathListOfTextAndAttr.push(f),xpathListOfTextAndAttr.push("//*[name()='"+h+"']")):xpathListOfTextAndAttr.push("//"+h),e&&(e.includes("'")||e.includes("\u2019")?(xpathListOfTextAndAttr.push('[text()="'+e+'"]'),xpathListOfTextAndAttr.push('[starts-with(text(),"'+e+'")]'),xpathListOfTextAndAttr.push('[.="'+e+'"]'),xpathListOfTextAndAttr.push('[contains(text(),"'+
e+'")]'),xpathListOfTextAndAttr.push('[contains(.,"'+e+'")]')):(xpathListOfTextAndAttr.push("[text()='"+e+"']"),xpathListOfTextAndAttr.push("[starts-with(text(),'"+e+"')]"),xpathListOfTextAndAttr.push("[.='"+e+"']"),xpathListOfTextAndAttr.push("[contains(text(),'"+e+"')]"),xpathListOfTextAndAttr.push("[contains(.,'"+e+"')]"))),d&&(isNaN(d)||xpathListOfTextAndAttr.push("[text()="+b+"]"),b=0==b.indexOf("\n")?d:b,d.includes("'")||d.includes("\u2019")?(xpathListOfTextAndAttr.push('[text()="'+b+'"]'),
xpathListOfTextAndAttr.push('[starts-with(text(),"'+b+'")]'),xpathListOfTextAndAttr.push('[.="'+b+'"]'),xpathListOfTextAndAttr.push('[contains(text(),"'+d+'")]'),xpathListOfTextAndAttr.push('[contains(.,"'+d+'")]'),xpathListOfTextAndAttr.push('[normalize-space()="'+d+'"]'),xpathListOfTextAndAttr.push('normalize-space()="'+d+'"]'),xpathListOfTextAndAttr.push('[contains(normalize-space(),"'+d+'")]'),xpathListOfTextAndAttr.push('contains(normalize-space(),"'+d+'")]')):(xpathListOfTextAndAttr.push("[text()='"+
b+"']"),xpathListOfTextAndAttr.push("[starts-with(text(),'"+b+"')]"),xpathListOfTextAndAttr.push("[.='"+b+"']"),xpathListOfTextAndAttr.push("[contains(text(),'"+d+"')]"),xpathListOfTextAndAttr.push("[contains(.,'"+d+"')]"),xpathListOfTextAndAttr.push("[normalize-space()='"+d+"']"),xpathListOfTextAndAttr.push("normalize-space()='"+d+"']"),xpathListOfTextAndAttr.push("[contains(normalize-space(),'"+d+"')]"),xpathListOfTextAndAttr.push("contains(normalize-space(),'"+d+"')]"))));cssListOfTextAndAttr.push(h);
if(0!=a.attributes.length&&!c)for(d=0;d<a.attributes.length;d++)b=a.attributes[d].name,c=a.attributes[d].nodeValue,null==c||""==c||"xpath"===b||"xpathtest"===b||"xpathtest"===b||"onclick"===b||listOfTextAndAttr.includes(b)||(c.includes("'")||c.includes("\u2019")?(cssListOfTextAndAttr.push("["+b+'="'+c+'"]'),cssListOfTextAndAttr.push("["+b+'$="'+c+'"]'),cssListOfTextAndAttr.push("["+b+'^="'+c+'"]'),cssListOfTextAndAttr.push("["+b+'*="'+c+'"]'),elementInShadowDom||(xpathListOfTextAndAttr.push("[@"+
b+'="'+c+'"]'),xpathListOfTextAndAttr.push("@"+b+'="'+c+'"]')),elementInShadowDom||xpathListOfTextAndAttr.push("[contains(@"+b+',"'+c.trim()+'")]')):(cssListOfTextAndAttr.push("["+b+"='"+c+"']"),cssListOfTextAndAttr.push("["+b+"$='"+c+"']"),cssListOfTextAndAttr.push("["+b+"^='"+c+"']"),cssListOfTextAndAttr.push("["+b+"*='"+c+"']"),elementInShadowDom||(xpathListOfTextAndAttr.push("[@"+b+"='"+c+"']"),xpathListOfTextAndAttr.push("@"+b+"='"+c+"']")),elementInShadowDom||xpathListOfTextAndAttr.push("[contains(@"+
b+",'"+c.trim()+"')]")),"class"==b?cssListOfTextAndAttr.push("."+c.split(" ").join(".")):"id"==b&&cssListOfTextAndAttr.push("#"+c));if(xpathListOfTextAndAttr){absXpathForInspected=createAbsXpath(a)[0];d=absXpathForInspected.split("[")[absXpathForInspected.split("[").length-1].split("]")[0];xpathListOfTextAndAttr.push("[position()="+d+"]");xpathListOfTextAndAttr.push("[last()]");for(d=f?2:1;d<xpathListOfTextAndAttr.length;d++){c=0;try{var g=f?f:"//"+h;c="["!=xpathListOfTextAndAttr[d].charAt(0)?_document.evaluate(g+
"["+xpathListOfTextAndAttr[d],_document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength:_document.evaluate(g+xpathListOfTextAndAttr[d],_document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength;xpathListOfTextAndAttr[d]=c+"-sanjayMatchingNode-"+xpathListOfTextAndAttr[d]}catch(l){}}c=_document.evaluate(g,_document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength;xpathListOfTextAndAttr[0]=c+"-sanjayMatchingNode-"+xpathListOfTextAndAttr[0];f&&(xpathListOfTextAndAttr[1]=
c+"-sanjayMatchingNode-"+xpathListOfTextAndAttr[1])}if(cssListOfTextAndAttr){for(d=1;d<cssListOfTextAndAttr.length;d++){c=0;try{c="."==cssListOfTextAndAttr[d].charAt(0)||"#"==cssListOfTextAndAttr[d].charAt(0)?cssSelectorMatchingNode(a,cssListOfTextAndAttr[d]):cssSelectorMatchingNode(a,h+cssListOfTextAndAttr[d]),cssListOfTextAndAttr[d]=c+"-sanjayMatchingNode-"+cssListOfTextAndAttr[d]}catch(l){}}c=cssSelectorMatchingNode(a,cssListOfTextAndAttr[0]);cssListOfTextAndAttr[0]=c+"-sanjayMatchingNode-"+cssListOfTextAndAttr[0]}xpathListOfTextAndAttr.sort();
cssListOfTextAndAttr.sort();xpathListOfTextAndAttr=placeZerosAtEnd(xpathListOfTextAndAttr);cssListOfTextAndAttr=placeZerosAtEnd(cssListOfTextAndAttr);f=[];f=[];f=[];f=[];f=[];cssListOfTextAndAttr.push("abc-sanjayMatchingNode-:first-child");cssListOfTextAndAttr.push("abc-sanjayMatchingNode-:last-child");cssListOfTextAndAttr.push("abc-sanjayMatchingNode-:nth-child()");cssListOfTextAndAttr.push("abc-sanjayMatchingNode-:nth-last-child()");cssListOfTextAndAttr.push("abc-sanjayMatchingNode-:first-of-type");
cssListOfTextAndAttr.push("abc-sanjayMatchingNode-:last-of-type");cssListOfTextAndAttr.push("abc-sanjayMatchingNode-:nth-of-type()");cssListOfTextAndAttr.push("abc-sanjayMatchingNode-:nth-last-of-type()");xpathListOfTextAndAttr.push("abc-sanjayMatchingNode-sibling::");xpathListOfTextAndAttr.push("abc-sanjayMatchingNode-contains()");xpathListOfTextAndAttr.push("abc-sanjayMatchingNode-starts-with");xpathListOfTextAndAttr.push("abc-sanjayMatchingNode-ends-with");f=getPrecedingSiblings(a);0<f.length&&
(xpathListOfTextAndAttr.push("abc-sanjayMatchingNode-preceding::"),xpathListOfTextAndAttr.push("abc-sanjayMatchingNode-preceding-sibling::"),xpathListOfTextAndAttr.push("abc-sanjayMatchingNode-]/preceding-sibling::"));for(d=0;d<f.length;d++)xpathListOfTextAndAttr.includes("abc-sanjayMatchingNode-preceding-sibling::"+f[d])||xpathListOfTextAndAttr.push("abc-sanjayMatchingNode-preceding-sibling::"+f[d]);f=getFollowingSiblings(a);0<f.length&&(xpathListOfTextAndAttr.push("abc-sanjayMatchingNode-following::"),
xpathListOfTextAndAttr.push("abc-sanjayMatchingNode-following-sibling::"),xpathListOfTextAndAttr.push("abc-sanjayMatchingNode-]/following-sibling::"));for(d=0;d<f.length;d++)0==d&&cssListOfTextAndAttr.push("abc-sanjayMatchingNode- + "+f[d]),xpathListOfTextAndAttr.includes("abc-sanjayMatchingNode-following-sibling::"+f[d])||cssListOfTextAndAttr.includes("abc-sanjayMatchingNode- ~ "+f[d])||(cssListOfTextAndAttr.push("abc-sanjayMatchingNode- ~ "+f[d]),xpathListOfTextAndAttr.push("abc-sanjayMatchingNode-following-sibling::"+
f[d]));a.parentNode&&(xpathListOfTextAndAttr.push("abc-sanjayMatchingNode-]/.."),xpathListOfTextAndAttr.push("abc-sanjayMatchingNode-parent::"),xpathListOfTextAndAttr.push("abc-sanjayMatchingNode-]/parent::"),xpathListOfTextAndAttr.push("abc-sanjayMatchingNode-parent::"+a.parentNode.nodeName.toLowerCase()));f=getAllChildren(a);0<f.length&&(xpathListOfTextAndAttr.push("abc-sanjayMatchingNode-child::"),xpathListOfTextAndAttr.push("abc-sanjayMatchingNode-]/child::"));for(d=0;d<f.length;d++)xpathListOfTextAndAttr.includes("abc-sanjayMatchingNode-child::"+
f[d])||cssListOfTextAndAttr.includes("abc-sanjayMatchingNode- > "+f[d])||(cssListOfTextAndAttr.push("abc-sanjayMatchingNode- > "+f[d]),xpathListOfTextAndAttr.push("abc-sanjayMatchingNode-child::"+f[d]));f=getAllAncestors(a);0<f.length&&(xpathListOfTextAndAttr.push("abc-sanjayMatchingNode-ancestor::"),xpathListOfTextAndAttr.push("abc-sanjayMatchingNode-]/ancestor::"));for(d=0;d<f.length;d++)xpathListOfTextAndAttr.includes("abc-sanjayMatchingNode-ancestor::"+f[d])||xpathListOfTextAndAttr.push("abc-sanjayMatchingNode-ancestor::"+
f[d]);f=getAllDescendants(a);0<f.length&&(xpathListOfTextAndAttr.push("abc-sanjayMatchingNode-]/descendant::"),xpathListOfTextAndAttr.push("abc-sanjayMatchingNode-descendant::"));for(d=0;d<f.length;d++)xpathListOfTextAndAttr.includes("abc-sanjayMatchingNode-descendant::"+f[d])||cssListOfTextAndAttr.includes("abc-sanjayMatchingNode- "+f[d])||(cssListOfTextAndAttr.push("abc-sanjayMatchingNode- "+f[d]),xpathListOfTextAndAttr.push("abc-sanjayMatchingNode-descendant::"+f[d]));listOfTextAndAttr.push(xpathListOfTextAndAttr);
listOfTextAndAttr.push(cssListOfTextAndAttr);_document!==document?chrome.runtime.sendMessage({count:frameOriframe}):h.includes("svg")||isSVGChild(a)?chrome.runtime.sendMessage({count:"svgelement"}):elementInShadowDom?chrome.runtime.sendMessage({count:"shadowdom"}):chrome.runtime.sendMessage({count:"notIframe"});if(isFirefox)chrome.runtime.sendMessage({count:listOfTextAndAttr});else return listOfTextAndAttr;listOfTextAndAttr=[];xpathListOfTextAndAttr=[];cssListOfTextAndAttr=[]}var listOfAttr={};
function getListOfAttr(a){for(var b=chooseAttrsForXpath[0],c,d,e=0;e<a.attributes.length;e++)c=a.attributes[e].name,d=a.attributes[e].nodeValue,null==d||""==d||"style"===c&&"style"!==b||"id"===c||"xpath"===c||"xpathtest"===c||chooseAttrsForXpath.includes("without"+c)&&b!=c||(listOfAttr[c]=d);return listOfAttr}
function buildRelXpath(a,b){var c=chooseAttrsForXpath[0],d=!1,e=b.nodeName.toLowerCase(),f=e.includes("body")?"":[].reduce.call(b.childNodes,function(v,u){return v+(3===u.nodeType?u.textContent:"")},"").trim();if(f.includes("  ")||f.includes("\n")||f.match(/[^\u0000-\u00ff]/))d=!0;if(f.includes("  ")||f.includes("\n"))f=deleteGarbageFromInnerText(f);e.includes("svg")&&(e="*");f.includes("'")?(f=f.split("  ")[0],dotText='[contains(.,"'+f+'")]',equalsText='[normalize-space()="'+f+'"]',containsText=
50<f.length||d?'[contains(text(),"'+f.slice(0,50)+'")]':'[normalize-space()="'+f+'"]'):(f=f.split("  ")[0],dotText="[contains(.,'"+f+"')]",equalsText="[normalize-space()='"+f+"']",containsText=50<f.length||d?"[contains(text(),'"+f.slice(0,50)+"')]":"[normalize-space()='"+f+"']");equalsText=containsText;if(chooseAttrsForXpath.includes("withouttext")||generateCssSelectorFlag)f="";if(f&&("a"==e||"button"==e||"label"==e||"h"==e.charAt(0))){var h="//"+e+equalsText,g=a.evaluate(h,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,
null).snapshotLength;if(1===g){g="//"+e+dotText;g=a.evaluate(g,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength;if(1===g)return h;g=b.firstChild.textContent;g=deleteGarbageFromInnerText(g);var l="//"+e+("[normalize-space()='"+g+"']");g=a.evaluate(l,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength;if(1===g)return l}}if(e.includes("html")||e.includes("body"))return"//"+e+tempXpath;var k=g="";var m={};if(!k)for(var p=0;p<b.attributes.length;p++)d=b.attributes[p].name,
g=b.attributes[p].nodeValue,null==g||""==g||"style"===d&&"style"!==c||"id"===d||"xpath"===d||"xpathtest"===d||chooseAttrsForXpath.includes("without"+d)&&c!=d||(m[d]=g);p=Object.keys(m).length;if(b.getAttribute(c)&&"id"!==c.toLowerCase()||""===b.id||!chooseAttrsForXpath.includes("withid")&&"id"!==c.toLowerCase())if(0!=p){var q=l="";for(d=0;d<p;d++){l=tempXpath;c in m?(g=c,k=m[g]):"placeholder"in m?(g="placeholder",k=m[g]):"title"in m?(g="title",k=m[g]):"name"in m?(g="name",k=m[g]):"value"in m?(g="value",
k=m[g]):"aria-label"in m?(g="aria-label",k=m[g]):"alt"in m?(g="alt",k=m[g]):"for"in m?(g="for",k=m[g]):"data-label"in m?(g="data-label",k=m[g]):"date-fieldlabel"in m?(g="date-fieldlabel",k=m[g]):"data-displaylabel"in m?(g="data-displaylabel",k=m[g]):"role"in m?(g="role",k=m[g]):"type"in m?(g="type",k=m[g]):"class"in m?(g="class",k=m[g]):(g=Object.keys(m)[0],k=m[g],isAlphaNumeric(k)&&(k=g=""));k=deleteLineGap(k);delete m[g];if(null!=k&&""!=k&&"xpath"!==g){var t="//"+e,r=h="";k.includes("  ")&&(k=k.split("  ")[k.split("  ").length-
1],containsFlag=!0);h=k.includes("'")?" "!==k.charAt(0)&&" "!==k.charAt(k.length-1)&&!containsFlag||xpathForCss?"//"+e+"[@"+g+'="'+k+'"]':"//"+e+"[contains(@"+g+',"'+k.trim()+'")]':" "!==k.charAt(0)&&" "!==k.charAt(k.length-1)&&!containsFlag||xpathForCss?"//"+e+"[@"+g+"='"+k+"']":"//"+e+"[contains(@"+g+",'"+k.trim()+"')]";r=h+l;g=a.evaluate(r,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength;if(1===g){if(r.includes("@href")&&!c.includes("href")||r.includes("@src")&&!c.includes("src")&&
f)if(n="//"+e+containsText+l,g=a.evaluate(n,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength,0===g){if(h="//"+e+equalsText+l,g=a.evaluate(h,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength,1===g)return h}else if(1===g)return n;return r}if(f)if(n="//"+e+containsText+l,g=a.evaluate(n,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength,0===g){h="//"+e+equalsText+l;g=a.evaluate(h,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength;if(1===
g)return h;1<g?l=h:0===g&&(l=r)}else if(1===g){g="//"+e+dotText+l;g=a.evaluate(g,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength;if(1===g)return n;g=b.firstChild.textContent;g=deleteGarbageFromInnerText(g);k="[normalize-space()='"+g+"']";r="//"+e+k+l;g=a.evaluate(r,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength;if(1===g)return r;l=h+k+l;g=a.evaluate(l,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength;if(1===g)return l}else{n="//"+e+"[contains(text(),'"+
f.slice(0,50)+"')]"+l;g=a.evaluate(n,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength;if(1===g)return n;n=h+containsText+l;g=a.evaluate(n,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength;if(0===g){if(h=h+equalsText+l,g=a.evaluate(h,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength,1===g)return h}else{if(1===g)return n;if(k.includes("/")||f.includes("/"))k.includes("/")&&(n=t+containsText+l),f.includes("/")&&(n=n.replace(containsText,""));l=n}}else l=
r,k.includes("/")&&(l="//"+e)}else if(f){n="//"+e+containsText+l;g=a.evaluate(n,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength;if(0===g){if(h="//"+e+equalsText+l,g=a.evaluate(h,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength,1===g)return h}else{if(1===g)return n;n="//"+e+"[contains(text(),'"+f.slice(0,50)+"')]"+l;g=a.evaluate(n,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength;if(1===g)return n}l=n}else if(null==k||""==k||g.includes("xpath"))l=
"//"+e+l;0==d&&(q=l)}tempXpath=q}else if(""==k&&f&&!e.includes("script"))if(n="//"+e+containsText+tempXpath,g=a.evaluate(n,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength,0===g){if(tempXpath="//"+e+equalsText+tempXpath,g=a.evaluate(tempXpath,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength,1===g)return tempXpath}else{if(1===g)return n;n="//"+e+"[contains(text(),'"+f.slice(0,50)+"')]"+tempXpath;g=a.evaluate(n,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength;
if(1===g)return n;tempXpath=n}else tempXpath="//"+e+tempXpath;else{d=b.id;d=deleteLineGap(d);tempXpath="//"+e+"[@id='"+d+"']"+tempXpath;g=a.evaluate(tempXpath,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength;if(1===g)return tempXpath;if(f&&0===b.getElementsByTagName("*").length){var n="//"+e+containsText+tempXpath;g=a.evaluate(n,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength;if(0===g){if(h="//"+e+equalsText+tempXpath,g=a.evaluate(h,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,
null).snapshotLength,1===g)return h}else if(1===g)return n}}e=0;f=b.parentNode.childNodes;for(p=0;p<f.length;p++){c=f[p];if(c===b)if(indexes.push(e+1),tempXpath=buildRelXpath(a,b.parentNode),tempXpath.includes("/")){g=a.evaluate(tempXpath,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength;if(1===g)return tempXpath;tempXpath="/"+tempXpath.replace(/\/\/+/g,"/");d=/\/+/g;for(m=/[^[\]]+(?=])/g;null!=(match=d.exec(tempXpath));)matchIndex.push(match.index);for(d=0;d<indexes.length;d++)if(0===
d?(g=tempXpath.slice(matchIndex[matchIndex.length-1]),null!=(match=m.exec(g))?(g=g.replace(m,indexes[d]).split("]")[0]+"]",tempXpath=tempXpath.slice(0,matchIndex[matchIndex.length-1])+g):tempXpath=tempXpath+"["+indexes[d]+"]"):(g=tempXpath.slice(matchIndex[matchIndex.length-(d+1)],matchIndex[matchIndex.length-d]),null!=(match=m.exec(g))?(g=g.replace(m,indexes[d]),tempXpath=tempXpath.slice(0,matchIndex[matchIndex.length-(d+1)])+g+tempXpath.slice(matchIndex[matchIndex.length-d])):tempXpath=tempXpath.slice(0,
matchIndex[matchIndex.length-d])+"["+indexes[d]+"]"+tempXpath.slice(matchIndex[matchIndex.length-d])),g=a.evaluate(tempXpath,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength,1===g){e=/([a-zA-Z])([^/]*)/g;f=tempXpath.match(e).length;for(d+=1;d<f-1;d++){g=tempXpath.match(/\/([^\/]+)\/?$/)[1];m=tempXpath.match(e);m.splice(f-d,1,"/");c="";for(p=0;p<m.length-1;p++)c=m[p]?c+"/"+m[p]:c+"//"+m[p];c=(c+"/"+g).replace(/\/\/+/g,"//");c=c.replace(/\/\/+/g,"/");c=c.replace(/\/+/g,"//");g=a.evaluate(c,
a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength;1===g&&(tempXpath=c)}return tempXpath.replace("//html","")}}else return tempXpath;1===c.nodeType&&c.nodeName.toLowerCase()===b.nodeName.toLowerCase()&&e++}}function removeLineBreak(a){a&&(a=0<a.split("\n")[0].length?a.split("\n")[0]:a.split("\n")[1]);return a}
function formContextRelXpath(a,b){var c=[].reduce.call(b.childNodes,function(k,m){return k+(3===m.nodeType?m.textContent:"")},"").trim();c=removeLineBreak(c);c=c.split("/")[0].trim();var d=b.nodeName.toLowerCase();d.includes("svg")&&(d="*");c.includes("'")?(c=c.split("  ")[0],containsText=20<c.length|doubleSpaceOrJunk?'[contains(text(),"'+c.slice(0,25)+'")]':'[normalize-space()="'+c+'"]',dotText='[contains(.,"'+c+'")]',equalsText='[normalize-space()="'+c+'"]'):(c=c.split("  ")[0],containsText=20<
c.length|doubleSpaceOrJunk?"[contains(text(),'"+c.slice(0,25)+"')]":"[normalize-space()='"+c+"']",dotText="[contains(.,'"+c+"')]",equalsText="[normalize-space()='"+c+"']");equalsText=doubleSpaceOrJunk?containsText:equalsText;generateCssSelectorFlag&&(c="");if(c&&("a"==d||"button"==d||"label"==d||"h"==d.charAt(0))){var e="//"+d+equalsText,f=a.evaluate(e,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength;if(1===f){f=a.evaluate("//"+d+dotText,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,
null).snapshotLength;if(1===f)return e;f=b.firstChild.textContent;f=deleteGarbageFromInnerText(f);var h="//"+d+("[normalize-space()='"+f+"']");f=a.evaluate(h,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength;if(1===f)return h}}if(d.includes("html")||d.includes("body"))return"//"+d+tempXpath;e=f="";var g={};if(""!==b.id){f=b.id;f=removeLineBreak(f);tempXpath="//"+d+"[@id='"+f+"']"+tempXpath;f=a.evaluate(tempXpath,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength;if(1===
f)return tempXpath;if(c&&0===b.getElementsByTagName("*").length)if(g="//"+d+containsText,f=a.evaluate(g,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength,0===f){if(e="//"+d+equalsText,f=a.evaluate(e,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength,1===f)return e}else if(1===f)return g}else if(0!=b.attributes.length){if(!e)for(h=0;h<b.attributes.length;h++)f=b.attributes[h].name,e=b.attributes[h].nodeValue,e.includes("/")||null==e||""==e||"style"===f||"id"===f||"xpath"===
f||"xpathtest"===f||(g[f]=e);f="placeholder"in g?"placeholder":"title"in g?"title":"value"in g?"value":"name"in g?"name":"aria-label"in g?"aria-label":"alt"in g?"alt":"for"in g?"for":"data-label"in g?"data-label":"date-fieldlabel"in g?"date-fieldlabel":"data-displaylabel"in g?"data-displaylabel":"role"in g?"role":"type"in g?"type":"class"in g?"class":Object.keys(g)[0];e=g[f];e=removeLineBreak(e);if(null!=e&&""!=e&&"xpath"!==f){var l="//"+d+tempXpath;h="";e.includes("  ")&&(e=e.split("  ")[e.split("  ").length-
1],containsFlag=!0);h=e.includes("'")?" "===e.charAt(0)||" "===e.charAt(e.length-1)||containsFlag?"//"+d+"[contains(@"+f+',"'+e.trim()+'")]'+tempXpath:"//"+d+"[@"+f+'="'+e+'"]'+tempXpath:" "===e.charAt(0)||" "===e.charAt(e.length-1)||containsFlag?"//"+d+"[contains(@"+f+",'"+e.trim()+"')]"+tempXpath:"//"+d+"[@"+f+"='"+e+"']"+tempXpath;f=a.evaluate(h,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength;if(1===f){if(h.includes("@href")&&!userAttr.includes("href")||h.includes("@src")&&!userAttr.includes("src")&&
c)if(g="//"+d+containsText,f=a.evaluate(g,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength,0===f){if(e="//"+d+equalsText,f=a.evaluate(e,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength,1===f)return e}else if(1===f)return g;return h}if(c)if(g="//"+d+containsText,f=a.evaluate(g,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength,0===f){e="//"+d+equalsText;f=a.evaluate(e,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength;if(1===f)return e;
tempXpath=1<f?e:h}else{if(1===f)return g;g=h+containsText;f=a.evaluate(g,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength;if(0===f){if(e=h+equalsText,f=a.evaluate(e,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength,1===f)return e}else{if(1===f)return g;if(e.includes("/")||c.includes("/"))e.includes("/")&&(g=l+containsText),c.includes("/")&&(g=g.replace(containsText,""));tempXpath=g}}else tempXpath=h,e.includes("/")&&(tempXpath="//"+d+l)}else if(c){g="//"+d+containsText;
f=a.evaluate(g,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength;if(0===f){if(e="//"+d+equalsText,f=a.evaluate(e,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength,1===f)return e}else if(1===f)return g;tempXpath=g+tempXpath}else if(null==e||""==e||f.includes("xpath"))tempXpath="//"+d+tempXpath}else if(""==e&&c&&!d.includes("script"))if(g="//"+d+containsText+tempXpath,f=a.evaluate(g,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength,0===f){if(tempXpath=
"//"+d+equalsText+tempXpath,f=a.evaluate(tempXpath,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength,1===f)return tempXpath}else{if(1===f)return g;tempXpath=g}else tempXpath="//"+d+tempXpath;d=0;e=b.parentNode.childNodes;for(h=0;h<e.length;h++){g=e[h];if(g===b)if(indexes.push(d+1),tempXpath=formContextRelXpath(a,b.parentNode),tempXpath.includes("/")){f=a.evaluate(tempXpath,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength;if(1===f)return tempXpath;tempXpath="/"+tempXpath.replace(/\/\/+/g,
"/");f=/\/+/g;for(l=/[^[\]]+(?=])/g;null!=(match=f.exec(tempXpath));)matchIndex.push(match.index);for(c=0;c<indexes.length;c++)if(0===c?(f=tempXpath.slice(matchIndex[matchIndex.length-1]),null!=(match=l.exec(f))?(f=f.replace(l,indexes[c]).split("]")[0]+"]",tempXpath=tempXpath.slice(0,matchIndex[matchIndex.length-1])+f):tempXpath=tempXpath+"["+indexes[c]+"]"):(f=tempXpath.slice(matchIndex[matchIndex.length-(c+1)],matchIndex[matchIndex.length-c]),null!=(match=l.exec(f))?(f=f.replace(l,indexes[c]),tempXpath=
tempXpath.slice(0,matchIndex[matchIndex.length-(c+1)])+f+tempXpath.slice(matchIndex[matchIndex.length-c])):tempXpath=tempXpath.slice(0,matchIndex[matchIndex.length-c])+"["+indexes[c]+"]"+tempXpath.slice(matchIndex[matchIndex.length-c])),f=a.evaluate(tempXpath,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength,1===f){d=/([a-zA-Z])([^/]*)/g;e=tempXpath.match(d).length;for(c+=1;c<e-1;c++){f=tempXpath.match(/\/([^\/]+)\/?$/)[1];l=tempXpath.match(d);l.splice(e-c,1,"/");g="";for(h=0;h<l.length-
1;h++)g=l[h]?g+"/"+l[h]:g+"//"+l[h];g=(g+"/"+f).replace(/\/\/+/g,"//");g=g.replace(/\/\/+/g,"/");g=g.replace(/\/+/g,"//");f=a.evaluate(g,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength;1===f&&(tempXpath=g)}return tempXpath.replace("//html","")}}else return tempXpath;1===g.nodeType&&g.nodeName.toLowerCase()===b.nodeName.toLowerCase()&&d++}}var chooseAttrsForXpath=[],shadowDOMOpenOrClosed="open";
function isInShadow(a){for(a=a&&a.parentNode;a;){if("[object ShadowRoot]"===a.toString())return shadowDOMOpenOrClosed=a.mode.toString(),!0;a=a.parentNode}return!1}
function createRelXpath(a,b){elementInShadowDom&&!iframeXPathFlag&&(inspectedElement=a);chooseAttrsForXpath=b.toString().split(",");var c="",d=[];try{_document=a.ownerDocument}catch(h){return d.push("0 element matching."),d.push("0"),d}var e=a.nodeName.toLowerCase();if(e.includes("#comment"))c="This is a comment and selectors can't be generated for comment.";else if(e.includes("::"))c="This is a pseudo element and selectors can't be generated for pseudo element.";else if(e.includes("style")||e.includes("script"))c=
"This is a "+e+" tag. For "+e+" tag, no need to write xpath. :P";else if(elementInShadowDom&&!iframeXPathFlag)c="This element is inside Shadow DOM and for such elements XPath won't support.",c=shadowDOMOpenOrClosed.includes("closed")?"This element is inside closed Shadow DOM which is inaccessible so for such elements we can't verify/write selectors.":c;else try{c=absXpath.includes("/*[local-name")?buildRelXpathForSVG(_document,a):createOptimizedRelXpath(_document,a)}catch(h){frameOriframe&&createAbsXpath(a),
c=absXpath}tempXpath="";try{var f=_document.evaluate(c,_document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength}catch(h){f=0}d.push(c);d.push(f);(c.includes("@id=")||c.includes("contains(@id"))&&isAttributeDynamic(c,"id")&&d.push("id");(c.includes("@class=")||c.includes("contains(@class"))&&isAttributeDynamic(c,"class")&&d.push("class");(c.includes("@name=")||c.includes("contains(@name"))&&isAttributeDynamic(c,"name")&&d.push("name");return d}
function optimizeXpath(a,b){for(var c=b.split("//"),d=c.length,e=b.match(/[^[\]]+(?=])/g),f=1,h=e.length-1;0<h&&!(f++,3<e[h].length);h--);h=b.split("//"+c[d-f])[1];e=0;try{e=a.evaluate(h,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength}catch(g){return b}if(1===e)return h;for(d-=f;0<d;d--){f=b.replace("//"+c[d],"");try{e=a.evaluate(f,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength,1===e&&(b=f)}catch(g){break}}return b}
function getElementNodename(a){var b="";a.classList.length&&(b=[a.nodeName.toLowerCase()],a=a.attributes["class"].value.trim(),a=a.replace(/  +/g," "),b.push(a.split(" ").join(".")),b=b.join("."));return b}
function getElementChildNumber(a){var b={},c,d=a.parentNode;var e=d.children.length;for(c=0;c<e;c++)if(d.children[c].classList.length){var f=d.children[c].classList[0];b[f]?b[f].push(d.children[c]):b[f]=[d.children[c]]}c=Object.keys(b).length||-1;f={childIndex:-1,childLen:e};b[Object.keys(b)[0]]===e?(f.childIndex=Array.prototype.indexOf.call(b[a.classList[0]],a),f.childLen=b[Object.keys(b)[0]].length):c&&-1!==c&&c!==e?(f.childIndex=Array.prototype.indexOf.call(d.children,a),f.childLen=b[Object.keys(b)[0]].length):
-1===c&&(f.childIndex=Array.prototype.indexOf.call(d.children,a),f.childLen=e);return f}function parents(a,b){var c;if(void 0===b)b=[];else{var d=getElementChildNumber(a);(c=getElementNodename(a))?(1<=d.childLen&&-1!==d.childIndex&&(c+=":nth-child("+(d.childIndex+1)+")"),b.push(c)):5>b.length&&(c=a.nodeName.toLowerCase(),-1!==d.childIndex&&(c+=":nth-child("+(d.childIndex+1)+")"),b.push(c))}return"BODY"!==a.nodeName?parents(a.parentNode,b):b}
function buildAbsCssSelector(a){if("html"===a.nodeName.toLowerCase())return"html";if("body"===a.nodeName.toLowerCase())return"body";if("#document-fragment"===a.nodeName.toLowerCase())return"";for(var b=a.parentNode.children,c=0;c<b.length;c++)if(b[c]===a){var d=buildAbsCssSelector(a.parentNode)+" > "+a.nodeName.toLowerCase()+":nth-child("+(c+1)+")";d=">"==d.trim().charAt(0)?d.trim().slice(1):d;break}return d}var xpathForCss=!1,generateCssSelectorFlag=!1;
function createCssSelector(a,b){xpathForCss=!0;elementInShadowDom&&!iframeXPathFlag&&(inspectedElement=a);var c=[],d=0,e="",f=chooseAttrsForXpath[0];try{a||(e="element is inside iframe & it is not supported by SelectorsHub currently. Please write CSS manually.",d=0);if(shadowDOMOpenOrClosed.includes("closed"))return e="element is inside iframe & it is not supported by SelectorsHub currently. Please write CSS manually.",d=0,c.push(e),c.push(d),c;var h=a.nodeName.toLowerCase();if(h.includes("style")||
h.includes("script"))e="This is "+h+" tag. For "+h+" tag, no need to write selector. :P",d=0;if(""!==a.id&&"id"==f)e="#"+a.id.trim();else if("body"==h||"head"==h||"html"==h)e=h;else if(elementInShadowDom||hostShadowDom){if(!(!a.className||h.includes("svg")||isSVGChild(a)||"class"!=f&&chooseAttrsForXpath.includes("withoutclass"))&&(e="."+replaceAll(a.className.trim()," ","."),d=cssSelectorMatchingNode(a,e),1===d))return c.push(e),c.push(d),c;if(h.includes("svg")||isSVGChild(a))return e=h,d=cssSelectorMatchingNode(a,
e),c.push(e),c.push(d),c;var g="",l="",k={};e=h;for(var m=0;m<a.attributes.length;m++)g=a.attributes[m].name,l=a.attributes[m].nodeValue,null==l||""==l||"style"===g&&"style"!==f||"id"===g||"xpath"===g||"xpathtest"===g||"cssselectortest"===g||chooseAttrsForXpath.includes("without"+g)&&f!=g||(k[g]=l);for(var p=0;p<Object.keys(k).length;p++)if(g=f in k?f:"placeholder"in k?"placeholder":"title"in k?"title":"value"in k?"value":"name"in k?"name":"aria-label"in k?"aria-label":"alt"in k?"alt":"for"in k?"for":
"data-label"in k?"data-label":"date-fieldlabel"in k?"date-fieldlabel":"data-displaylabel"in k?"data-displaylabel":"role"in k?"role":"type"in k?"type":"class"in k?"class":Object.keys(k)[0],l=k[g],l=deleteLineGap(l),delete k[g],null!=l&&""!=l&&"css"!==g&&"xpath"!==g&&(e=l.includes("'")?e+"["+g+'="'+l.trim()+'"]':e+"["+g+"='"+l+"']",d=cssSelectorMatchingNode(a,e),1===d))return c.push(e),c.push(d),c}else if(!absXpath.includes("/*[local-name")){if(a.className&&"class"==f){e="."+replaceAll(a.className.trim(),
" ",".");d=cssSelectorMatchingNode(a,e);if(1===d)return c.push(e),c.push(d),c;e=""}if(h.includes("svg")||isSVGChild(a))return e=h,d=cssSelectorMatchingNode(a,e),c.push(e),c.push(d),c;l=g="";k={};e=h;for(m=0;m<a.attributes.length;m++)g=a.attributes[m].name,l=a.attributes[m].nodeValue,null==l||""==l||"style"===g&&"style"!==f||"xpath"===g||"xpathtest"===g||"cssselectortest"===g||chooseAttrsForXpath.includes("without"+g)&&f!=g||(k[g]=l);for(p=0;p<Object.keys(k).length;p++)if(g=f in k?f:"id"in k?"id":
"placeholder"in k?"placeholder":"title"in k?"title":"value"in k?"value":"name"in k?"name":"aria-label"in k?"aria-label":"alt"in k?"alt":"for"in k?"for":"data-label"in k?"data-label":"date-fieldlabel"in k?"date-fieldlabel":"data-displaylabel"in k?"data-displaylabel":"role"in k?"role":"type"in k?"type":"class"in k?"class":Object.keys(k)[0],l=k[g],l=deleteLineGap(l),delete k[g],null!=l&&""!=l&&"css"!==g&&"xpath"!==g&&(e="id"==g?"#"+l.trim():"class"==g?"."+replaceAll(l.trim()," ","."):l.includes("'")?
e+"["+g+'="'+l.trim()+'"]':e+"["+g+"='"+l+"']",d=cssSelectorMatchingNode(a,e),1===d))return c.push(e),c.push(d),c;f=e="";generateCssSelectorFlag=!0;f=suggestedFlag||globalRelXpath.includes("normalize-space()")||globalRelXpath.includes("text()")||"relXpathOff"==relXpathChecked?createRelXpath(a,b)[0]:globalRelXpath;xpathForCss=generateCssSelectorFlag=!1;try{if(f.includes("@href")||f.includes("@src"))e=f.replace("//","").replace(/\[@/g,"[");else{var q=f.replace(/\/+/g,"//");q=q.split("//");f=/[^[\]]+(?=])/g;
for(m=1;m<q.length;m++){var t=q[m];if(t.includes("[")){var r=q[m].match(f)[0];t=4>r.length?q[m].split("[")[0]+":nth-child("+r+")":q[m].replace(/\[@/g,"[")}e=e+" "+t}}}catch(w){}d=cssSelectorMatchingNode(a,e)}d=cssSelectorMatchingNode(a,e);if(1!=d||absXpath.includes("/*[local-name"))if(e=buildAbsCssSelector(a),d=cssSelectorMatchingNode(a,e),1!=d){var n=parents(a,[]);n=n.reverse();var v=n.slice(n.length-1,n.length),u=n.slice(0,n.length-1);e="";e=0!=u.length?u.join(" ")+" > "+v:v}d=cssSelectorMatchingNode(a,
e)}catch(w){e=buildAbsCssSelector(a),d=cssSelectorMatchingNode(a,e)}c.push(e);c.push(d);return c}
function parentCssSelector(a,b){var c=a,d="";a.nodeName.toLowerCase();for(var e=absXpath.match(/[^[\]]+(?=])/g),f=e.length-1;0<=f;f--){var h=c.id?"#"+c.id:b.includes("withoutclass")||absXpath.includes("/*[local-name")||!c.className?c.nodeName.toLowerCase()+":nth-child("+e[f]+")":c.nodeName.toLowerCase()+"."+replaceAll(c.className.trim()," ",".")+":nth-child("+e[f]+")";var g=cssSelectorMatchingNode(a,d);if(1==g)return d;d=0==g?d?c.nodeName.toLowerCase()+" > "+d:c.nodeName.toLowerCase():d?h+" > "+d:
h;c=c.parentNode;if("body"===c.nodeName.toLowerCase())return"body > "+d}}function cssSelectorMatchingNode(a,b){var c=0;if(elementInShadowDom&&!iframeXPathFlag)try{c=a.getRootNode().host.shadowRoot.querySelectorAll(b).length}catch(d){c=0}else try{c=_document.querySelectorAll(b).length}catch(d){c=0}return c}
function createSelectorName(a){_document=a.ownerDocument;var b=_document!==document?"(inside iframe)":"",c="",d={};var e="";var f=a.nodeName.toLowerCase();if(f.includes("path")||"g"==f)for(;!a.nodeName.toLowerCase().includes("svg")&&(a=a.parentElement,f=a.nodeName.toLowerCase(),!f.includes("svg")););f.includes("svg")&&(a=a.parentElement);if(f.includes("pseudo"))return f=a.parentElement.className,e=f.includes("icon")?f.replace(/-/g,""):getComputedStyle(a,"").getPropertyValue("content"),e.trim()+b;
if("button input meter output progress select textarea".split(" ").includes(f)&&a.id)try{return e=_document.querySelector("label[for='"+a.id+"']").textContent,e.trim()+b}catch(k){}else if(f.includes("style")||f.includes("script")||f.includes("body")||f.includes("html")||f.includes("head")||f.includes("link")||f.includes("meta")||f.includes("title")||f.includes("comment"))try{return e=a.className?a.className.split(" ")[0]:a.id?a.id:f+"Tag",e.trim()+b}catch(k){}var h=a.textContent.trim();h&&2>h.length&&
(h=a.parentNode.textContent.trim());if(f.includes("label"))e=h;else if(0!=a.attributes.length){if(!c)for(var g=0;g<a.attributes.length;g++)e=a.attributes[g].name,c=a.attributes[g].nodeValue,null==c||""==c||e.includes("style")||e.includes("id")||e.includes("xpath")||(d[e]=c);c="";"placeholder"in d?c=d.placeholder:h.trim()?c=h:"aria-label"in d?c=d["aria-label"]:"name"in d?c=d.name:"value"in d?c=d.value:"title"in d?c=d.title:"alt"in d?c=d.alt:"for"in d?c=d["for"]:"data-label"in d?c=d["data-label"]:"date-fieldlabel"in
d?c=d["date-fieldlabel"]:"data-displaylabel"in d?c=d["data-displaylabel"]:"role"in d&&(c=d.role);e=c;if(!e&&(c="search remove delete close cancel plus add subtract minus cart home logo notification globe".split(" "),d=a.className.toLowerCase()))for(g=0;g<c.length;g++)d.includes(c[g])&&(e=c[g]+" icon")}if(!e||3>e.length){e=(e=h)?e:a.textContent.trim();if(!e){h=new WebPage(document);try{e=h.getLabel(a)}catch(k){}h=!1;if(e&&e.text&&e.text.length){h=e&&e.text&&Math.round(e.text.length/2);var l=e.text.slice(0,
h);h=l==e.text.slice(h)}h&&(e.text=l,e=e.text);e=e?e.text:""}!e&&a.parentElement?e=a.parentElement.textContent.trim():e||(e=f+"tag")}e||(a=a.parentElement,e=createSelectorName(a));e=e?e:"";e=e.includes("inside iframe")?e:e+b;return e.trim().substr(0,100)}
function createOptimizedRelXpath(a,b){var c="";try{c=buildRelXpath(a,b)}catch(f){tempXpath="",chooseAttrsForXpath=["withoutid","withoutclass"],c=buildRelXpath(a,b)}var d=/\/\/+/g,e=0;try{e=c.match(d).length}catch(f){}1<e&&c.includes("[")&&!c.includes("@href")&&!c.includes("@src")&&(c=optimizeXpath(a,c));void 0===c&&(c="It might be pseudo element/comment/inside iframe from cross-origin. XPath doesn't support for them.");return c}
function buildRelXpathForSVG(a,b){var c=chooseAttrsForXpath[0],d=b.nodeName.toLowerCase();tagFormat=d.includes("svg")?"//*[local-name()='"+d:"//*[name()='"+d;if(d.includes("svg")){try{d=tempXpath,tempXpath="",indexes=[],tempXpath=createOptimizedRelXpath(a,b.parentNode)+"//*[local-name()='svg']"+d,indexes=[]}catch(m){}return tempXpath}var e="",f={};d="";try{b.attributes.removeNamedItem("xpath"),d=b.attributes.length}catch(m){d=b.attributes.length}if(b.getAttribute(c)&&"id"!==c.toLowerCase()||""===
b.id||!chooseAttrsForXpath.includes("withid"))if(0<d){if(!e)for(d=0;d<b.attributes.length;d++){var h=b.attributes[d].name;e=b.attributes[d].nodeValue;null==e||""==e||"style"===h&&"style"!==c||"id"===h||"xpath"===h||(f[h]=e.trim().slice(0,10))}if(0<Object.keys(f).length)if(h=c in f?c:"placeholder"in f?"placeholder":"title"in f?"title":"value"in f?"value":"name"in f?"name":"type"in f?"type":"class"in f?"class":Object.keys(f)[0],e=f[h],e=deleteLineGap(e),null!=e&&""!=e&&"xpath"!==h){if(e.includes("  ")&&
(e=e.split("  ")[e.split("  ").length-1],containsFlag=!0),tempXpath=e.includes("'")?tagFormat+'" and contains(@'+h+',"'+e+'")]'+tempXpath:tagFormat+"' and contains(@"+h+",'"+e+"')]"+tempXpath,c=a.evaluate(tempXpath,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength,1===c)return tempXpath}else if(null==e||""==e||h.includes("xpath"))if(tempXpath=tagFormat+"'"+tempXpath,c=a.evaluate(tempXpath,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength,1===c)return tempXpath}else{if(tempXpath=
tagFormat+"']"+tempXpath,c=a.evaluate(tempXpath,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength,1===c)return tempXpath}else if(d=b.id,d=deleteLineGap(d),tempXpath=tagFormat+"' and @id='"+d+"']"+tempXpath,c=a.evaluate(tempXpath,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength,1===c)return tempXpath;e=0;f=b.parentNode.childNodes;for(d=0;d<f.length;d++){h=f[d];if(h===b)if(indexes.push(e+1),tempXpath=buildRelXpathForSVG(a,b.parentNode),tempXpath.includes("/")){c=a.evaluate(tempXpath,
a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength;if(1===c)return tempXpath;for(var g=absXpath.split("/*"),l=tempXpath.split("/*"),k=g.length-1;0<k;k--)if(tempXpath=tempXpath.replace(l[k],g[k]),c=a.evaluate(tempXpath,a,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength,1===c)return tempXpath}else return tempXpath;1===h.nodeType&&h.nodeName.toLowerCase()===b.nodeName.toLowerCase()&&e++}}var eventHandlers={};
function addListenersForStudio(a,b,c,d){c.handlerName=a;d||(d=!1);a=d?"C_"+b:b;eventHandlers[a]||(eventHandlers[a]=[]);eventHandlers[a].push(c)}function parseEventKey(a){return a.match(/^C_/)?{eventName:a.substring(2),capture:!0}:{eventName:a,capture:!1}}
function attachEvents(){if(!this.attached){this.attached=!0;this.eventListeners={};var a=this,b={},c;for(c in eventHandlers){b.$jscomp$loop$prop$eventKey$24=c;var d=function(g){return function(){var l=eventHandlers[g.$jscomp$loop$prop$eventKey$24],k=function(q){for(var t=0;t<l.length;t++)l[t].call(a,q)};this.window.document.addEventListener(f,k,h);this.eventListeners[g.$jscomp$loop$prop$eventKey$24]=k;var m=document.getElementsByTagName("iframe");if(m)for(var p=0;p<m.length;p++)m[p].contentDocument&&
m[p].contentDocument.addEventListener(f,k,h)}}(b),e=parseEventKey(b.$jscomp$loop$prop$eventKey$24),f=e.eventName,h=e.capture;d.call(this);browser.runtime.sendMessage(chrome.runtime.id,{data:"",message:"AttachStudio"});b={$jscomp$loop$prop$eventKey$24:b.$jscomp$loop$prop$eventKey$24}}}}
function deattachEvents(){if(this.attached){this.attached=!1;for(var a in this.eventListeners){var b=parseEventKey(a);this.window.document.removeEventListener(b.eventName,this.eventListeners[a],b.capture)}delete this.eventListeners}}window.onload=function(){browser.runtime.sendMessage(chrome.runtime.id,{type:"verification",data:[]})};function isAlphaNumeric(a){var b=/\d/;return/[a-zA-Z]/.test(a)&&b.test(a)||b.test(a)?!0:!1}
var recorderCommands={addSelection:"select",clickAt:"Click on",doubleClickAt:"Double click on",rightClick:"Right click on",select:"select",sendKeys:"Hit Enter",submit:"Hit Enter",type:"Enter"};
function record(a,b,c,d){c=void 0===c?"":c;if(d)return browser.runtime.sendMessage(chrome.runtime.id,{data:recorderCommands[a],type:"windowEvent",URL:window.location.href,dataText:"",relXpath:""}),!1;d=createSelectorName(b);try{var e=createRelXpath(b,attrArr)}catch(f){try{e=createAbsXpath(b)}catch(h){return!1}}d&&(d=d.slice(0,30),browser.runtime.sendMessage(chrome.runtime.id,{data:recorderCommands[a]+" "+d,type:"windowEvent",URL:window.location.href,dataText:c,relXpath:e?e[0]:"",planeLabel:d}))}
var allIframes={},iframeIndex=0;function getAlliframe(a){allIframes["doc"+iframeIndex]=a;var b=a.querySelectorAll("iframe");a=a.querySelectorAll("frame");b=0<b.length&&0<a.length?b.concat(a):0<b.length?b:a;allIframes["iframe"+iframeIndex]=b;for(a=0;a<b.length;a++){var c=b[a];try{if(c.contentWindow.document.querySelector("iframe")||c.contentWindow.document.querySelector("frame"))iframeIndex+=1,getAlliframe(c.contentWindow.document)}catch(d){}}}var parentiframeXpath=[],iframeXPathFlag=!1;
function getIframeXpath(a){getAlliframe(document);for(var b=Object.keys(allIframes).length,c,d=0;d<b;d++){var e=allIframes["iframe"+d];c=allIframes["doc"+d];for(var f=0;f<e.length;f++)if(e[f].contentDocument==a)return _document=c,iframeXPathFlag=!0,b=createRelXpath(e[f],",withid,withclass,withname,withplaceholder,withtext"),iframeXPathFlag=!1,0==parentiframeXpath.length&&(_document=a),c!=document&&parentiframeXpath.push(getIframeXpath(c)[0]),b}}
function getIframeSelector(a){for(var b=document.querySelectorAll(frameOriframe),c=0;c<b.length;c++)if(b[c].contentDocument==a)return b=createCssSelector(b[c],",withid,withclass,withname,withplaceholder,withtext"),_document=a,b}function isAttributeDynamic(a,b){var c=new RegExp("@+"+b+"+='(.*?)'","g"),d=a.match(new RegExp("@"+b+",'(.*?)'","g"));c=a.match(c);return isAlphaNumeric(d)?!0:isAlphaNumeric(c)}var typeTarget,typeLock=0,eventCaptured=0,prevTargetElement=null,inputTypes="text password file datetime datetime-local date month time week number range email url search tel color".split(" ");
addListenersForStudio("type","change",function(a){if(a.target.nodeName&&!preventType&&0==typeLock&&(typeLock=1)){prevTargetElement=a.target;var b=a.target.nodeName.toLowerCase(),c=a.target.type;if("input"==b&&0<=inputTypes.indexOf(c))if(0<a.target.value.length){if(record("type",a.target,a.target.value),eventCaptured=1,null!=enterTarget){a=a.target.parentElement;for(b=a.nodeName.toLowerCase();"form"!=b&&"body"!=b;)a=a.parentElement,b=a.nodeName.toLowerCase();"form"!=b||!a.hasAttribute("id")&&!a.hasAttribute("name")||
a.hasAttribute("onsubmit");record("sendKeys",enterTarget,null,!0);enterTarget=null}}else record("type",a.target,a.target.value);else"textarea"==b&&record("type",a.target,a.target.value)}typeLock=0});addListenersForStudio("type","input",function(a){typeTarget=a.target});var preventClickTwice=!1,clickCounter=0;
addListenersForStudio("clickAt","click",function(a){eventCaptured=0;clickCounter++;if(0==a.button&&!preventClick&&a.isTrusted){if(!preventClickTwice&&1===clickCounter){var b=a.target;do b=b.offsetParent;while(b);b=a.target;for(var c=b.getAttribute("type"),d=b.parentNode.nodeName,e=0;3>e;e++)try{var f=b.parentNode;"FORM"==f.nodeName&&(d=f.nodeName)}catch(h){}"INPUT"==b.nodeName||"SELECT"==b.nodeName&&("text"==c||"email"==c||"password"==c||"tel"==c||"number"==c||"FORM"==d&&!c)&&"radio"!=c&&"checkbox"!=
c||"FORM"==b.nodeName||"BODY"==b.nodeName||(prevTargetElement=a.target,record("clickAt",a.target));preventClickTwice=!0}setTimeout(function(){preventClickTwice=!1;clickCounter=0},200)}},!0);addListenersForStudio("doubleClickAt","dblclick",function(a){clickCounter=0;var b=a.target;"FORM"!=b.nodeName&&"BODY"!=b.nodeName&&record("doubleClickAt",a.target)},!0);
for(var focusTarget=null,focusValue=null,tempValue=null,preventType=!1,inp=document.getElementsByTagName("input"),i=0;i<inp.length;i++)0<=inputTypes.indexOf(inp[i].type)&&(inp[i].addEventListener("focus",function(a){focusTarget=a.target;tempValue=focusValue=focusTarget.value;preventType=!1}),inp[i].addEventListener("blur",function(a){tempValue=focusValue=focusTarget=null}));var preventClick=!1,enterTarget=null,varenterValue=null,tabCheck=null;
addListenersForStudio("sendKeys","keydown",function(a){if(a.target.nodeName){var b=a.keyCode,c=a.target.nodeName.toLowerCase(),d=a.target.type;if("input"==c&&0<=inputTypes.indexOf(d)){prevTargetElement=a.target;if(13==b){enterTarget=a.target;enterValue=enterTarget.value;c=a.target.parentElement;d=c.nodeName.toLowerCase();if(tempValue==enterTarget.value&&tabCheck==enterTarget)record("sendKeys",enterTarget,null,!0),enterTarget=null,preventType=!0;else if(focusValue==enterTarget.value){for(;"form"!=
d&&"body"!=d;)c=c.parentElement,d=c.nodeName.toLowerCase();"form"!=d||!c.hasAttribute("id")&&!c.hasAttribute("name")||c.hasAttribute("onsubmit")?record("sendKeys",enterTarget,null,!0):c.hasAttribute("id")?record("submit","id="+c.id,"",!0):c.hasAttribute("name")&&record("submit","name="+c.name,"",!0);enterTarget=null}if(typeTarget.nodeName&&!preventType&&(typeLock=1))if(c=typeTarget.nodeName.toLowerCase(),d=typeTarget.type,"input"==c&&0<=inputTypes.indexOf(d))if(0<typeTarget.value.length){if(record("type",
typeTarget,typeTarget.value),null!=enterTarget){c=typeTarget.parentElement;for(d=c.nodeName.toLowerCase();"form"!=d&&"body"!=d;)c=c.parentElement,d=c.nodeName.toLowerCase();"form"!=d||!c.hasAttribute("id")&&!c.hasAttribute("name")||c.hasAttribute("onsubmit")?record("sendKeys",enterTarget,null,!0):c.hasAttribute("id")?record("submit",[["id="+c.id,"id"]],"",!0):c.hasAttribute("name")&&record("submit",[["name="+c.name,"name"]],"",!0);enterTarget=null}}else record("type",typeTarget,typeTarget.value);
else"textarea"==c&&record("type",typeTarget,typeTarget.value);preventClick=!0;setTimeout(function(){preventClick=!1},500);setTimeout(function(){enterValue!=a.target.value&&(enterTarget=null)},50)}c=!1;38!=b&&40!=b||""==a.target.value||(null!=focusTarget&&focusTarget.value!=tempValue&&(c=!0,tempValue=focusTarget.value),c&&record("type",a.target,tempValue),setTimeout(function(){tempValue=focusTarget.value},250),record("sendKeys",a.target,"",!0),tabCheck=a.target);9==b&&tabCheck==a.target&&(record("sendKeys",
a.target,"",!0),preventType=!0)}}},!0);addListenersForStudio("contextMenu","contextmenu",function(a){var b=a.target;"FORM"!=b.nodeName&&"BODY"!=b.nodeName&&record("rightClick",a.target)},!0);var checkFocus=0;addListenersForStudio("editContent","focus",function(a){"true"==a.target.contentEditable&&(getEle=a.target,contentTest=getEle.innerHTML,checkFocus=1)},!0);browser.runtime.sendMessage({attachStudioRequest:!0})["catch"](function(a){});
function getOptionSelector(a){a=a.text.replace(/^ *(.*?) *$/,"$1");return a.match(/\xA0/)?"label=regexp:"+a.replace(/[\(\)\[\]\\\^\$\*\+\?\.\|\{\}]/g,function(b){return"\\"+b}).replace(/\s+/g,function(b){return b.match(/\xA0/)?1<b.length?"\\s+":"\\s":b}):a}function normalizeSpaces(a){if(browserVersion.isIE)return a;a=a.replace(/ +/g," ");var b=new RegExp(String.fromCharCode(160),"g");return browserVersion.isSafari?replaceAll(a,String.fromCharCode(160)," "):a.replace(b," ")}
function normalizeNewlines(a){return a.replace(/\r\n|\r/g,"\n")}function findClickableWebElement(a){if(!a.nodeName)return null;var b=a.nodeName.toLowerCase(),c=a.type;return a.hasAttribute("onclick")||a.hasAttribute("href")||"button"==b||"input"==b&&("submit"==c||"button"==c||"image"==c||"radio"==c||"checkbox"==c||"reset"==c)?a:null!=a.parentNode?findClickableWebElement(a.parentNode):null}
addListenersForStudio("select","focus",function(a){if(a.target.nodeName&&"select"==a.target.nodeName.toLowerCase()&&a.target.multiple){a=a.target.options;for(var b=0;b<a.length;b++)null==a[b]._wasSelected&&(a[b]._wasSelected=a[b].selected)}},!0);
addListenersForStudio("select","change",function(a){if(a.target.nodeName&&"select"==a.target.nodeName.toLowerCase())if(prevTargetElement=a.target,a.target.multiple)for(var b=a.target.options,c=0;c<b.length;c++){if(b[c]._wasSelected!=b[c].selected){var d=getOptionSelector(b[c]);b[c].selected?record("addSelection",a.target,d,!0):record("removeSelection",a.target,d,!0);b[c]._wasSelected=b[c].selected}}else record("select",a.target,getOptionSelector(a.target.options[a.target.selectedIndex]))});
function getText(a){var b="";browserVersion.isFirefox&&"1.5"<=browserVersion.firefoxVersion||browserVersion.isKonqueror||browserVersion.isSafari||browserVersion.isOpera?b=getTextContent(a):a.textContent?b=a.textContent:a.innerText&&(b=a.innerText);b=normalizeNewlines(b);b=normalizeSpaces(b);return b.trim()}
function getTextContent(a,b){if(a.style&&("hidden"==a.style.visibility||"none"==a.style.display))return"";if(3==a.nodeType){var c=a.data;b||(c=c.replace(/\n|\r|\t/g," "));return c}if(1==a.nodeType&&"SCRIPT"!=a.nodeName){var d=b||"PRE"==a.nodeName;c="";for(var e=0;e<a.childNodes.length;e++){var f=a.childNodes.item(e);c+=getTextContent(f,d)}if("P"==a.nodeName||"BR"==a.nodeName||"HR"==a.nodeName||"DIV"==a.nodeName)c+="\n";return c}return""}
function getInspectedElement(){var a=_document.querySelector("*[xpathtest]");a&&setTimeout(function(){a.removeAttribute("xpathtest")},2);return a}var globalRelXpath="";
function onInspectElementClick(a,b,c){var d="",e="",f="",h="",g="",l="",k="",m="",p="";elementInShadowDom=isInShadow(a);var q="";try{q=a.nodeName.toLowerCase()}catch(r){}if(""==_document||""==q)q=["Element inside cross-origin iframe. Copy Selectors by right click on element or open iframe src url in new tab.","0"];else if(q.includes("style")||q.includes("script"))q=["This is a "+q+" tag. For "+q+" tag, no need to write Selectors. :P","0"];else if(q.includes("#comment"))q=["This is a comment and selectors can't be generated for comment.",
"0"];else if(q.includes("::"))q=["This is a pseudo element and selectors will be generated for it's parentElement.","0"];else{d=createAbsXpath(a);absXpath=d[0];q=createRelXpath(a,b);globalRelXpath=q[0];try{e=createCssSelector(a,b)}catch(r){}g=createIdSelector(a);k=createNameSelector(a);l=createClassNameSelector(a);"a"===a.nodeName.toLowerCase()&&(f=createLinkTextSelector(a),h=createPartialLinkTextSelector(a));m=createTagNameSelector(a);"generatorAndEditorRecording"==c&&a&&(p=createSelectorName(a));
if(elementInShadowDom){var t=getAllShadowHost(a,b);elementInShadowDom=!0}}a=[];a.push(q);a.push(e);a.push(g);a.push(k);a.push(l);a.push(f);a.push(h);a.push(d);a.push(m);a.push(p);a.push(t);if(isFirefox)chrome.runtime.sendMessage({showInspected:!0,xpath:a});else return a}window.addEventListener("beforeunload",function(a){try{chrome.runtime.sendMessage({count:"pageReload"})}catch(b){}});var allShadowDomChildNodes=[],node="";
function replaceShadowDomsWithHtml(a){a=$jscomp.makeIterator(a.querySelectorAll("*"));for(var b=a.next();!b.done;b=a.next())if(b=b.value,b.shadowRoot){if(b.shadowRoot.querySelector("*[xpathtest='1']")){node=b.shadowRoot.querySelector("*[xpathtest='1']");setTimeout(function(){node.removeAttribute("xpathtest")},5);break}replaceShadowDomsWithHtml(b.shadowRoot)}return node}var hostShadowDom=!1;
function getAllShadowHost(a,b){for(var c=(a&&a.parentNode).getRootNode().host,d=[];c;)hostShadowDom=!0,elementInShadowDom=isInShadow(c),d.push(createCssSelector(c,b)[0]),c=(c&&c.parentNode).getRootNode().host;inspectedElement=a;return d}function executeJs(a){var b=[];b.push(a.outerHTML);return b};