var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};var devtoolsRegEx=/^chrome-devtools:\/\//,connections={},clickEnabled=!0,master={},API=chrome||browser,contentWindowId="",isFirefox="undefined"!==typeof InstallTrigger,browserType=chrome;isFirefox&&(browserType=browser);var messageToContentScript=function(a){browserType.tabs.sendMessage(a.tabId,a)};
browserType.runtime.onConnect.addListener(function(a){var b=function(c,d,e){c&&"DeattachStudio"===c.message&&(clickEnabled=!0);"init"==c.name?connections[c.tabId]=a:"active"==c.name?window.browserType.windows.update(contentWindowId,{focused:!0}):"openStudio"==c.name?clickEnabled?openStudioWindow():window.browserType.windows.update(contentWindowId,{focused:!0}):messageToContentScript(c)};a.onMessage.addListener(b);a.onDisconnect.addListener(function(c){c.onMessage.removeListener(b);for(var d=Object.keys(connections),
e=0,f=d.length;e<f;e++)if(connections[d[e]]==c){delete connections[d[e]];break}})});var relXpath="",relCssSelector="",jspath="",absXpath="",oldValue=[],contextOption="active",relXpathChecked="relXpathOn",cssSelectorChecked="cssSelectorOff",jspathChecked="jspathOff",absXpathChecked="absXpathOff";function deleteContextMenuItem(a){try{browserType.contextMenus.remove(a,function(){})}catch(b){}}
function createContextMenuItem(a,b){contextOption=browserType.contextMenus.create({title:a,id:b,parentId:"parent",contexts:["all"]});oldValue.push(contextOption)}
browserType.runtime.onMessage.addListener(function(a,b,c){a.contextMenu&&(contextMenu=a.contextMenu,browserType.storage.local.set({contextMenu:contextMenu},function(){}),setTimeout(function(){if(contextMenu.includes("inactive"))deletePreviousMenuItems();else try{deletePreviousMenuItems(),createContextMenu()}catch(d){}},100));a.relXpathChecked&&(relXpathChecked=a.relXpathChecked,browserType.storage.local.set({relXpathChecked:relXpathChecked},function(){}),"relXpathOff"==relXpathChecked?deleteContextMenuItem("parent1"):
(deleteContextMenuItem("parent1"),contextOption=browserType.contextMenus.create({title:"Copy Rel XPath",id:"parent1",parentId:"parent",contexts:["all"]}),oldValue.push(contextOption)));a.cssSelectorChecked&&(cssSelectorChecked=a.cssSelectorChecked,browserType.storage.local.set({cssSelectorChecked:cssSelectorChecked},function(){}),"cssSelectorOff"==cssSelectorChecked?deleteContextMenuItem("parent2"):(deleteContextMenuItem("parent2"),createContextMenuItem("Copy Rel cssSelector","parent2")));a.jspathChecked&&
(jspathChecked=a.jspathChecked,browserType.storage.local.set({jspathChecked:jspathChecked},function(){}),"jspathOff"==jspathChecked?deleteContextMenuItem("parent3"):(deleteContextMenuItem("parent3"),createContextMenuItem("Copy JS path","parent3")));a.absXpathChecked&&(absXpathChecked=a.absXpathChecked,browserType.storage.local.set({absXpathChecked:absXpathChecked},function(){}),"absXpathOff"==absXpathChecked?deleteContextMenuItem("parent4"):(deleteContextMenuItem("parent4"),createContextMenuItem("Copy abs XPath",
"parent4")));try{relXpath=a.contextSelectors[0],relCssSelector=a.contextSelectors[1],jspath=a.contextSelectors[2],absXpath=a.contextSelectors[3]}catch(d){}console.log(a.message);a&&"AttachStudio"===a.message&&(clickEnabled=!1);a&&"DeattachStudio"===a.message&&(clickEnabled=!0);if(b.tab)if(devtoolsRegEx.test(b.tab.url)){if("shown"===a.event||"hidden"===a.event)b=b.tab.id,b in connections&&connections[b].postMessage(a);messageToContentScript(a)}else b=b.tab.id,b in connections&&connections[b].postMessage(a);
return!0});var deletePreviousMenuItems=function(){if(0<oldValue.length)try{for(var a=0;a<oldValue.length;a++)browserType.contextMenus.remove(oldValue[a],function(){})}catch(b){}oldValue=[]},installURL="https://www.youtube.com/watch?v=jV84DRg96qs",updateURL="https://www.selectorshub.com/changelog/",uninstallURL="https://www.selectorshub.com/uninstall/",manifest=browserType.runtime.getManifest();browserType.runtime.setUninstallURL(uninstallURL,function(){});
var installedListener=function(a){"install"==a.reason?(installNotification(),browserType.notifications.onClicked.addListener(onClickInstallNoti)):"update"==a.reason&&(updateNotification(),browserType.notifications.onClicked.addListener(onClickNoti))};function onClickInstallNoti(){browserType.tabs.create({url:installURL})}function onClickNoti(){browserType.tabs.create({url:updateURL})}
var updateNotification=function(){browserType.notifications.create({title:"SelectorsHub",message:"Click here to see the Changelog of new version "+manifest.version,type:"basic",iconUrl:"logo-128.png"})},installNotification=function(){browserType.notifications.create("onInstalled",{title:"SelectorsHub",message:"Refresh the opened tab & watch the video tutorial to make best use of SelectorsHub",type:"basic",iconUrl:"logo-128.png"})};browserType.runtime.onInstalled.addListener(installedListener);
var contextMenu="active";
browserType.storage.local.get("contextMenu",function(a){(contextMenu=a.contextMenu)?contextMenu.includes("inactive")?deletePreviousMenuItems():(browserType.storage.local.get("relXpathChecked",function(b){relXpathChecked=b.relXpathChecked;"relXpathOff"==relXpathChecked&&deleteContextMenuItem("parent1")}),browserType.storage.local.get("cssSelectorChecked",function(b){cssSelectorChecked=b.cssSelectorChecked;"cssSelectorOff"==cssSelectorChecked&&deleteContextMenuItem("parent2")}),browserType.storage.local.get("jspathChecked",
function(b){jspathChecked=b.jspathChecked;"jspathOff"==jspathChecked&&deleteContextMenuItem("parent3")}),browserType.storage.local.get("absXpathChecked",function(b){absXpathChecked=b.absXpathChecked;"absXpathOff"==absXpathChecked&&deleteContextMenuItem("parent4")}),createContextMenu()):createContextMenu()});
browserType.contextMenus.onClicked.addListener(function(a,b){"parent1"==a.menuItemId?copyValueToClipboard(relXpath):"parent2"==a.menuItemId?copyValueToClipboard(relCssSelector):"parent3"==a.menuItemId?copyValueToClipboard(jspath):"parent4"==a.menuItemId&&copyValueToClipboard(absXpath)});function copyValueToClipboard(a){var b=document.createElement("textarea");b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)}
function createContextMenu(){contextOption=browserType.contextMenus.create({id:"parent",title:"SelectorsHub",contexts:["all"]});oldValue.push(contextOption);"relXpathOn"==relXpathChecked&&(contextOption=browserType.contextMenus.create({title:"Copy Relative XPath",id:"parent1",parentId:"parent",contexts:["all"]}),oldValue.push(contextOption));"cssSelectorOn"==cssSelectorChecked&&(contextOption=browserType.contextMenus.create({title:"Copy Relative cssSelector",id:"parent2",parentId:"parent",contexts:["all"]}),
oldValue.push(contextOption));"jspathOn"==jspathChecked&&(contextOption=browserType.contextMenus.create({title:"Copy JS path",id:"parent3",parentId:"parent",contexts:["all"]}),oldValue.push(contextOption));"absXpathOn"==absXpathChecked&&(contextOption=browserType.contextMenus.create({title:"Copy abs XPath",id:"parent4",parentId:"parent",contexts:["all"]}),oldValue.push(contextOption))}
function openStudioWindow(){browser.windows.create({url:API.runtime.getURL("testCaseStudio/studioWindow.html"),type:"popup",height:600,width:400}).then(function(a){master[a.id]=a;contentWindowId=a.id;browser.tabs.sendMessage(contentWindowId,{type:"studioId",studioId:a});browser.tabs.query({active:!0,windowId:a.id,status:"complete"}).then(function(b){1!=b.length&&(master[a.id]=a.id)})})["catch"](function(a){console.log(a)})};