var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};
$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};$jscomp.polyfillUnisolated=function(a,b,c,d){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))return;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,d){var e=a.split(".");a=1===e.length;d=e[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<e.length-1;f++){var g=e[f];if(!(g in d))return;d=d[g]}e=e[e.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?d[e]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==c&&(void 0===$jscomp.propertyToPolyfillSymbol[e]&&(c=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+c+"$"+e),$jscomp.defineProperty(d,$jscomp.propertyToPolyfillSymbol[e],{configurable:!0,writable:!0,value:b})))};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};
$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};
$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype["return"]=function(a){this.abruptCompletion_={"return":a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){var c=$jscomp.makeIterator(a),d=c.next();$jscomp.generator.ensureIteratorResultIsObject_(d);if(d.done)this.yieldResult=d.value,this.nextAddress=b;else return this.yieldAllIterator_=c,this.yield(d.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,c){c?this.finallyContexts_[c]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){var c=this.finallyContexts_.splice(b||0)[0];if(c=this.abruptCompletion_=this.abruptCompletion_||c){if(c.isException)return this.jumpToErrorHandler_();void 0!=c.jumpTo&&this.finallyAddress_<c.jumpTo?(this.nextAddress=c.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(c){return{value:c,done:!0}},a,this.context_["return"]);this.context_["return"](a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,c){try{var d=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(d);if(!d.done)return this.context_.stop_(),d;var e=d.value}catch(f){return this.context_.yieldAllIterator_=null,this.context_.throw_(f),this.nextStep_()}this.context_.yieldAllIterator_=null;c.call(this.context_,e);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a["return"],done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this["throw"]=function(b){return a.throw_(b)};this["return"]=function(b){return a.return_(b)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){var c=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&a.prototype&&$jscomp.setPrototypeOf(c,a.prototype);return c};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(d){return a.next(d)}function c(d){return a["throw"](d)}return new Promise(function(d,e){function f(g){g.done?d(g.value):Promise.resolve(g.value).then(b,c).then(f,e)}f(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
var idAttr=document.querySelector(".idAttr"),classAttr=document.querySelector(".classAttr"),nameAttr=document.querySelector(".nameAttr"),placeholder=document.querySelector(".placeholder"),textXpath=document.querySelector(".text-xpath"),checkboxes=document.querySelectorAll(".attributeChoice"),tablePlaceholder=document.querySelector(".tablePlaceholder"),copyAllButton=document.querySelector(".copyAllButton"),copyAllXpath=document.querySelector(".copyAllXpath"),copyAllData=document.querySelector(".copyAllData"),
toggleHeader=document.getElementById("toggleHeader"),fileName=document.querySelector("#downloadFileName"),recordButton=document.getElementById("record"),recordIcon=document.getElementById("recordIcon"),element=document.getElementById("records-grid"),helperText=document.getElementById("helperText"),save_btn=document.getElementById("save_btn"),toggleElement=document.getElementById("inputToggle"),xpathInput=document.getElementById("xpathInput"),clearTestCase=document.getElementById("clearTestCase"),
alwaysTop=document.getElementById("alwaysTop"),pauseBtnToolTip=document.querySelector(".pauseBtn.toolTip"),toggleToolTip=document.querySelector(".toggle.toolTip"),isFirefox="undefined"!==typeof InstallTrigger,browserType=chrome;isFirefox&&(browserType=browser);tablePlaceholder.innerText="1. Now keep performing your manual steps on your website.\r\n2. All your actions will be recorded here.\r\n3. For each step relative xpath will be generated along with driver command.\r\n4. You can update the driver command or turn off.\r\n5. Once you are done, save the test case or copy all rows by clicking on header copy icon.\r\n6. By default it will save file with First test case name but you can update this.";
var recording=!0,steps=[],xpathText="",senderId="",atttrArr="[, withid,withclass,withname,withplaceholder,withtext]",interval=null,userEmail="Anonymous";
chrome.runtime.onMessage.addListener(function(a,b,c){senderId=b.tab.id;a&&"windowEvent"===a.type&&recording&&"Click on aTag"!==a.data&&(steps.length||steps.push({step:"Open website",relXpath:"",dataText:a.URL,planeLabel:a.URL}),steps.push({step:a.data,relXpath:a.relXpath,dataText:a.dataText,planeLabel:a.planeLabel}),displayRows(),notifyMe("selectorsHub",a.data));a&&"recorderAttr"===a.type&&setAttr(a.data);a&&"verification"===a.type&&recording&&(senderId?browser.tabs.sendMessage(senderId,{openStudio:!0}):
null)});
function displayRows(){element.innerHTML=null;document.querySelector(".tablePlaceholder").style.display="none";var a=!!toggleElement.classList.contains("active");if(steps&&steps.length)if(command="",a&&xpathInput.value&&xpathInput.value.toLowerCase().includes("xpathvalue"))for(var b=0;b<steps.length;b++){a=command="";var c=!1;steps[b].relXpath&&steps[b].relXpath.length&&(command=xpathInput.value.replace(/xpathvalue/i,steps[b].relXpath),a=xpathInput.value.replace(/xpathvalue/i,""+steps[b].relXpath));xpathInput.value&&
xpathInput.value.toLowerCase().includes("labelvalue")&&(c=!0);element.innerHTML+="\n                <tr class=\"tableRow\">\n                    <td class='fixedColumns'>\n                        <div class='tableData'>"+(b+1)+"</div>\n                    </td>\n                    <td class='fixedColumns'>\n                        <div title=\""+steps[b].step+'" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" contenteditable="true" class=\'tableData allSteps\'>'+steps[b].step+
'</div>\n                    </td>\n                    <td title="'+steps[b].dataText+'" class=\'fixedColumns\'>\n                        <div autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" contenteditable="true" class=\'tableData dataCol\'>'+steps[b].dataText+'</div>\n                    </td>\n                    <td class=\'fixedColumnsEven\'>\n                        <div class="tableData xpathData" autocomplete="off" id="label-'+b+'" autocorrect="off" autocapitalize="off" spellcheck="false" contenteditable="true" title="'+
command+'">'+a+"</div>\n                    </td>\n                    <td id=\"actionCol\">\n                        <button id='addStep'></button>\n                        <button id='delButton'></button>\n                    </td>\n                </tr>\n                ";c&&(document.querySelector("#label-"+b).textContent=a.replace(/labelvalue/i,toCamelCase(steps[b].planeLabel)))}else for(a=0;a<steps.length;a++)element.innerHTML+="\n                <tr class=\"tableRow\">\n                    <td class='fixedColumns'>\n                        <div class='tableData'>"+
(a+1)+"</div>\n                    </td>\n                    <td class='fixedColumns'>\n                        <div title=\""+steps[a].step+'" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" contenteditable="true" class=\'tableData allSteps\'>'+steps[a].step+'</div>\n                    </td>\n                    <td title="'+steps[a].dataText+'" class=\'fixedColumns\'>\n                        <div autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" contenteditable="true" class=\'tableData dataCol\'>'+
steps[a].dataText+'</div>\n                    </td>\n                    <td class=\'fixedColumnsEven\'>\n                        <div autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" contenteditable="true" title="'+steps[a].relXpath+'" class="tableData xpathData xpathColor">'+steps[a].relXpath+"</div>\n                    </td>\n                    <td id=\"actionCol\">\n                        <button id='addStep'></button>\n                        <button id='delButton'></button>\n                    </td>\n                </tr>\n                ";
clickCell();0==steps.length&&(document.querySelector(".tablePlaceholder").style.display="")}function toCamelCase(a){return a.replace(/_/g," ").replace(/\s(.)/g,function(b){return b.toUpperCase()}).replace(/\s/g,"").replace(/^(.)/,function(b){return b.toLowerCase()})}
function clickCell(){for(var a=document.getElementById("records-grid").rows,b=0;b<a.length;b++)a[b].cells[4].childNodes[3].addEventListener("click",function(c){steps.splice(this.parentNode.parentNode.rowIndex-1,1);displayRows()}),a[b].cells[4].childNodes[1].addEventListener("click",function(c){steps.splice(this.parentNode.parentNode.rowIndex,0,{step:"",relXpath:"",dataText:""});displayRows()}),a[b].childNodes[7].addEventListener("input",function(c){c.data?(steps[this.parentNode.rowIndex-1].relXpath=
this.innerText,this.childNodes[1].classList.remove("removeOutline")):this.childNodes[1].classList.add("removeOutline")}),a[b].childNodes[3].addEventListener("input",function(c){c.data?(steps[this.parentNode.rowIndex-1].step=this.innerText,this.childNodes[1].classList.remove("removeOutline")):this.childNodes[1].classList.add("removeOutline")}),a[b].childNodes[5].addEventListener("input",function(c){c.data?(steps[this.parentNode.rowIndex-1].dataText=this.innerText,this.childNodes[1].classList.remove("removeOutline")):
this.childNodes[1].classList.add("removeOutline")})}
toggleElement.addEventListener("click",function(){var a=document.querySelector(".inputFeildContainer"),b=document.querySelector("#updatetitle");this.classList.contains("active")?(this.classList.remove("active"),this.classList.add("inactive"),xpathInput.classList.add("hidden"),xpathInput.classList.remove("show"),toggleToolTip.textContent="Click to enable command",helperText.innerText="Add custom driver command",toggleHeader.innerText="Xpath",a.classList.remove("showElement"),a.classList.add("remove"),
b.title="Click to copy all xpaths"):(this.classList.remove("inactive"),this.classList.add("active"),toggleToolTip.textContent="Click to disable command",xpathInput.classList.add("show"),xpathInput.classList.remove("hidden"),helperText.innerText="",toggleHeader.innerText="Command",a.classList.add("showElement"),a.classList.remove("remove"),b.title="Click to copy all commands");displayRows()});
recordButton.addEventListener("click",function(a){recording?(recording=!1,recordIcon.style.backgroundImage="url(../../icons/pause_black.svg)",recordIcon.style.animation="none",pauseBtnToolTip.textContent="Click to start recording.",senderId?browser.tabs.sendMessage(senderId,{stopRecording:!0}):null):(recording=!0,recordIcon.style.animation="blinker 1.0s cubic-bezier(.5, 0, 1, 1) infinite alternate",recordIcon.style.backgroundImage="url(../../icons/stopped.svg)",pauseBtnToolTip.textContent="Click to stop recording.",
senderId?browser.tabs.sendMessage(senderId,{openStudio:!0}):null)});
save_btn.addEventListener("click",function(a){a=toggleToolTip.textContent.includes("Click to enable command")?"XPath":"Command";if(steps&&steps.length){a=[["Step","Data",a]];var b=document.querySelectorAll(".allSteps"),c=document.querySelectorAll(".dataCol"),d=document.querySelectorAll(".xpathData"),e=steps.map(function(f,g){return{relXpath:d[g].innerText,dataText:c[g].innerText,step:b[g].innerText}});e=e.map(function(f){return[f.step,f.dataText,f.relXpath]});a=a.concat(e);e=fileName.innerText.replace(/\s/g,
"");browser.tabs.sendMessage(senderId,{type:"downloadReport",data:a,fileName:e||"testcase"})}else showSnackbar("No data to save")});function showSnackbar(a){var b=document.querySelector("#snackbar");b.innerText=a;b.className="show";setTimeout(function(){b.className=b.className.replace("show","")},2E3)}
xpathInput.addEventListener("keyup",function(a){xpathText=a.target.value;if(13==a.keyCode){if(!this.value.toLowerCase().includes("xpathvalue")){this.classList.add("wrongXpath");showSnackbar("xpathValue keyword should be there in the command.");return}displayRows();updateCPAttr()}this.value.toLowerCase().includes("xpathvalue")?this.value.toLowerCase().includes("xpathvalue")&&this.classList.remove("wrongXpath"):this.classList.add("wrongXpath")});
window.onload=function(a){browser.tabs.query({}).then(function(b){b.forEach(function(c){return $jscomp.asyncExecutePromiseGeneratorProgram(function(d){return d.yield(browser.tabs.sendMessage(c.id,{openStudio:!0}),0)})})})};window.onbeforeunload=function(a){browser.tabs.query({}).then(function(b){b.forEach(function(c){return $jscomp.asyncExecutePromiseGeneratorProgram(function(d){return d.yield(browser.tabs.sendMessage(c.id,{closed:!0}),0)})})});window.removeEventListener("beforeunload")};
function notifyMe(a,b){console.log("notification-"+Notification.permission);"granted"===Notification.permission&&((new Notification("SelectorsHub",{icon:"../../icons/tcStudio_black.svg",body:b})).onclick=function(){window.focus()})}clearTestCase.addEventListener("click",function(a){document.querySelector(".tablePlaceholder").style.display="";element.innerHTML=null;steps=[]});copyAllButton.addEventListener("click",function(){copyAllRowsToClipboard()});copyAllXpath.addEventListener("click",function(){copyAllXpathToClipboard()});
copyAllData.addEventListener("click",function(){copyAllDataToClipboard()});function copyAllXpathToClipboard(){var a=document.createElement("textarea");a.id="t";a.style.height=0;document.body.appendChild(a);for(var b=document.querySelectorAll(".xpathData"),c=0;c<b.length;c++)a.value=a.value+"\n"+b[c].innerText;document.querySelector("#t").select();document.execCommand("copy");document.body.removeChild(a)}
function copyAllDataToClipboard(){var a=document.createElement("textarea");a.id="t";a.style.height=0;document.body.appendChild(a);for(var b=document.querySelectorAll(".dataCol"),c=0;c<b.length;c++)a.value=a.value+"\n"+b[c].innerText;document.querySelector("#t").select();document.execCommand("copy");document.body.removeChild(a)}
function copyAllRowsToClipboard(a){document.querySelector(a);a=document.createElement("textarea");a.id="t";a.style.height=0;document.body.appendChild(a);for(var b=document.querySelectorAll(".allSteps"),c=0;c<b.length;c++)a.value=a.value+"\n"+b[c].innerText;document.querySelector("#t").select();document.execCommand("copy");document.body.removeChild(a)}
function attributeChoicesOption(){atttrArr=","+(idAttr.checked?"withid":"withoutid")+","+(classAttr.checked?"withclass":"withoutclass")+","+(nameAttr.checked?"withname":"withoutname")+","+(placeholder.checked?"withplaceholder":"withoutplaceholder")+","+(textXpath.checked?"withtext":"withouttext");browser.tabs.sendMessage(senderId,{attrArray:atttrArr})}checkboxes.forEach(function(a){a.addEventListener("change",function(){attributeChoicesOption();updateCPAttr()})});
function setAttr(a){idAttr.checked=a.idChecked;classAttr.checked=a.classChecked;nameAttr.checked=a.nameChecked;placeholder.checked=a.placeholderChecked;textXpath.checked=a.textChecked}function updateCPAttr(){browser.tabs.sendMessage(senderId,{name:"updateCPAttr",data:{idChecked:idAttr.checked,classChecked:classAttr.checked,nameChecked:nameAttr.checked,placeholderChecked:placeholder.checked,textChecked:textXpath.checked}})}
var attributeFilter=document.querySelector(".attributeFilter"),attrFilterBtn=document.querySelector(".attrFilterBtn");
attrFilterBtn.addEventListener("click",function(a){"none"===attributeFilter.style.display?(browserType.storage.local.set({studioAttributeFilter:"active"},function(){}),attributeFilter.style.display="flex",attrFilterBtn.classList.remove("inactive"),attrFilterBtn.classList.add("active")):(browserType.storage.local.set({studioAttributeFilter:"inactive"},function(){}),attributeFilter.style.display="none",attrFilterBtn.classList.remove("active"),attrFilterBtn.classList.add("inactive"))});
browserType.storage.local.get(["studioAttributeFilter"],function(a){"active"==a.studioAttributeFilter&&(attributeFilter.style.display="flex",attrFilterBtn.classList.remove("inactive"),attrFilterBtn.classList.add("active"))});